---
title: "Differential taxa analysis"
author: "Jincheng Wang"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, 
                      warning = FALSE, message = FALSE)
# Loading library here
library(conflicted)
library(tidyverse)
library(extrafont)
library(Ternary)
library(phyloseq)
sessionInfo()
conflict_prefer("filter", "dplyr")

np = switch(Sys.info()[['sysname']], Windows = 1, Darwin = 4)

fig_path = "tmp_figs/"

col_birthmode = c("#377EB8", "#4DAF4A", "#E41A1C")
names(col_birthmode) = c("Vag", "CSseed", "CS")
```

## examing songbird model fit
```{r, eval=FALSE}
dat_path = '../data/diff-analysis-new'
dat_files = list.files(dat_path, pattern = "grid-search-all-allowed-models", full.names = T)
dat_models = lapply(dat_files, function(x){read_tsv(x) %>% select(-X1) %>% filter(best=="Yes")}) %>% data.table::rbindlist(fill = T)
```

## Summarizing songbird resulst
When performing songbird parameter summarization, following parameters were tried:
```{r}
songbird_pp = readClipboard() %>% str_split(., pattern = "\t", simplify = T)
colnames(songbird_pp) = songbird_pp[1, ]
songbird_pp = songbird_pp[-1, ] %>% as.data.frame() %>% mutate(across(.fns = trimws)) %>% print()
```

```{r}
songbird_model_fits <- read.table(file = "../data/diff-analysis-new/TP-w-training-grid-search-all-allowed-models.tsv", header = T, sep = "\t")[, -1]

songbird_best_models <- songbird_model_fits %>% filter(best=="Yes") %>%  # select best model under different formula
    filter(grepl("country", formula)) # since all the formula with country as covariate performed better
songbird_best_models_print <- songbird_best_models %>% 
    mutate(model_CV = round(CV, 1),
           null_CV = round(baseline_CV, 1),
           q_squared = round(q_squared, 3)) %>%
    select(body_site, days, min_features:differential_prior,
           model_CV, null_CV, q_squared) %>%
    arrange(body_site, days) %>% 
    write.csv(file = "../results/Extended_Data_Table_Songbird_model_fit_statistics.csv", quote = F, row.names = F)
    
songbird_rsl <- read.csv("../data/diff-analysis-new/TP-w-training-best-model-processed.tsv", 
                     sep = "\t", fill = F) %>% select(-1, -2, -starts_with("country")) %>%
    filter(grepl("country", model.para))

songbird_wk <- songbird_rsl %>% 
    select(body_site_days, featureid, 
           starts_with("P."), Taxon, 
           starts_with("centered"),
           feature.frequency, seeding.effectiveness) %>%
    rename(P.VD = P.Vaginal., P.CSR = P.CS.seeded., P.CS = P.CS.) %>%
    separate(body_site_days, into = c(NA, "body_site", "days"), sep = "-") %>% 
    mutate(days = as.numeric(days)) %>%
    group_by(body_site, days) %>% 
    mutate(seeding.effectiveness.scale = pnorm(as.numeric(scale(seeding.effectiveness, center = mean(seeding.effectiveness), scale = T)))) %>%
    ungroup() %>%
    arrange(body_site, days, desc(seeding.effectiveness.scale)) %>%
    mutate(featureid = factor(featureid, levels = unique(featureid)), 
           Taxon = gsub(" ", "", Taxon),
           Taxon = gsub("__", "_", Taxon)) %>%
    separate(Taxon, into = c("k", "p", "c", "o", "f", "g", "s"), sep = ";",
             remove = F,
             fill = "right") %>%
    mutate(across(k:s, ~ifelse(is.na(.x), "-", .x)))

# check the distribution of seeding-effectiveness score
ggplot(songbird_wk, aes(x = seeding.effectiveness)) +
    geom_histogram(aes(color = as.factor(days), fill = as.factor(days)), alpha = 0.3, position = "identity") +
    facet_grid(body_site ~ .)

songbird_wk %>% group_by(body_site, days) %>% summarise(stats = Hmisc::smean.sd(seeding.effectiveness) %>% paste(collapse = "--"))


songbird_wk_0.9 <- songbird_wk %>% 
    filter(seeding.effectiveness.scale>=0.9, feature.frequency>=0.1) %>%
    mutate(across(.cols = c(P.CS:P.VD, feature.frequency:seeding.effectiveness.scale), ~round(., 3)))

songbird_wk_0.9 %>% pivot_wider(id_cols = c(body_site, days, Taxon, k:s), names_from = NULL, values_from = c(Diff.CS, Diff.CSR, seeding.effectiveness.scale, feature.frequency, P.VD, P.CSR, P.CS), names_repair = "minimal") %>% arrange(body_site, days, Taxon) %>% View

songbird_wk_0.8 <- songbird_wk %>% 
    filter(seeding.effectiveness.scale>=0.8, feature.frequency>=0.1) %>%
    mutate(across(.cols = c(P.CS:P.VD, feature.frequency:seeding.effectiveness.scale), ~round(., 3)))

songbird_wk_0.8 %>% group_by(body_site, days) %>% summarize(N = n())

```
### Ternary plot
```{r}

plot_ternary = function(bb, dd){
    TernaryPlot(point = "up",  alab = "Cesaren-seeded <---", 
                blab = "Vaginal --->", clab = "Cesarean <---",
                lab.col = c( "#4DAF4A", "#377EB8", "#E41A1C"),
                
                grid.minor.lines = 0,
                grid.col = c( "#4DAF4A", "#377EB8", "#E41A1C"),
                grid.lty = "dotted",
                
                #padding = 0,
                
                main = paste0("Day ", dd),
                
                axis.col = "black",
                axis.labels=seq(0, 1, by = 0.1),
                
                clockwise = F)
    dat_ternary = songbird_wk %>% filter(body_site==bb, days==dd) %>% 
        select(P.CSR, P.VD, P.CS, seeding.effectiveness.scale)
    dat_ternary$col = circlize::colorRamp2(seq(0, 1, 0.1), 
                                           colors = colorspace::divergingx_hcl(11, palette = "Tropic"))(dat_ternary$seeding.effectiveness.scale)
    
    AddToTernary(points, dat_ternary[, 1:3], pch = 21, cex = 0.7,
                 bg = dat_ternary$col)
}

for (bb in c("Feces", "Forearm", "Mouth")){
    par(mfrow = c(2, 2), mar = rep(0.1, 4))
    for (dd in c(2, 30, 120, 180)){
        plot_ternary(bb, dd)
    }
    dev.copy2pdf(file = paste0(fig_path, "songbird_ternary_plot_", bb, ".pdf"),
                 width = 7, height = 10, useDingbats = F, pointsize = 10)
    dev.off()
    
    # create the legend
    par(mar = c(3, 0.1, 2, 0.1))
    image(x = seq(0,1,len=100), 
          y = 1,
          z = matrix(1:100,ncol=1),
          main = "Seeding efficacy",
          cex.main = 1, 
          col = colorspace::divergingx_hcl(100, palette = "Tropic"),
          axes = FALSE, xlab = "", ylab = "")
    axis(1, at = seq(0.1, 0.9, 0.2), cex.axis = 1)
    dev.copy2pdf(file = paste0(fig_path, "songbird_ternary_plot_", bb, "_legend.pdf"), width = 3, height = 1, pointsize = 8, useDingbats = F)
    dev.off()
}

# create the main plot

```
### Plot against differentials
```{r}
bb = "Feces"
load("tmp_all_phylo.Rdata")
songbird_wk2 <- songbird_wk %>%
    filter(feature.frequency>=0.1, p!="p_", c!="c_", o!="o_", f!="f_",
           p!="-", c!="-", o!="-", f!="-")
```
#### check bacteroides
```{r}
bacteroides <- songbird_wk2 %>% filter(g == "g_Bacteroides")
for (bb in c("Feces", "Forearm", "Mouth")){
    for (dd in c(2, 30, 120, 180)){
        #dd=2
        dat <- bacteroides %>% filter(body_site==bb, days ==dd) %>%
            mutate(x = paste(p, c, o, f, g, sep = ";"))
        dat_ft <- all_phylo$ASV[[paste0("Baby-", bb, "-", dd, ".0")]] %>% 
            transform_sample_counts(., function(x){x / sum(x)}) %>%
            otu_table() %>% as.matrix() %>% as.data.frame() %>%
            rownames_to_column(var = "ASV") %>%
            filter(ASV %in% dat$featureid) %>% 
            pivot_longer(-1, names_to = "sample_name", values_to = "rel_a") %>% 
            filter(rel_a>0) %>%
            merge(., dat %>% select(featureid, k:s, x), by.x = "ASV", by.y = 1) %>%
            merge(., sample_data(all_phylo$ASV[[paste0("Baby-", bb, "-", dd, ".0")]]) %>%
                      as.matrix() %>% as.data.frame(),
                  by.x = "sample_name", by.y = 0)
        
        p = ggplot(dat_ft, aes(x = ASV, y = rel_a, fill = birth_mode_ms)) +
            geom_boxplot() +
            coord_flip() +
            scale_x_discrete(breaks = dat$featureid, labels = dat$s) +
            geom_text(data = dat, aes(x = featureid, y = max(dat_ft$rel_a), 
                                      label = centered.diff.CS), inherit.aes = F) +
            labs(x = "Bacterloides ASV", title = paste(bb, "Day", dd))
        print(p)
    }
}
```
#### All genus
```{r}
for (bb in c("Feces", "Forearm", "Mouth")){
    for (dd in c(2, 30, 120, 180)){
        #dd=2
        dat <- songbird_wk2 %>% filter(body_site==bb, days ==dd) %>%
            mutate(x = paste(p, c, o, f, g, sep = ";"))
        dat_ft <- all_phylo$ASV[[paste0("Baby-", bb, "-", dd, ".0")]] %>% 
            transform_sample_counts(., function(x){x / sum(x)}) %>%
            otu_table() %>% as.matrix() %>% as.data.frame() %>%
            rownames_to_column(var = "ASV") %>%
            filter(ASV %in% dat$featureid) %>% 
            pivot_longer(-1, names_to = "sample_name", values_to = "rel_a") %>% 
            filter(rel_a>0) %>%
            merge(., dat %>% select(featureid, k:s, x), by.x = "ASV", by.y = 1)
        
        x.order = dat %>% group_by(x) %>% summarise(MM = median(centered.diff.CS)) %>% arrange(desc(MM))
        
        p <- dat %>% mutate(x = factor(x, levels = unique(x.order$x))) %>%
            ggplot(aes(x = x, y = -centered.diff.CS)) +
            annotate("rect", ymin = -Inf, ymax = 0, xmin = -Inf, xmax = Inf, fill = "#E41A1C", alpha = 0.1) +
            annotate("rect", ymin = 0, ymax = Inf, xmin = -Inf, xmax = Inf, fill = "#377EB8", alpha = 0.1) +
            geom_hline(yintercept = 0, color = "grey") +
            geom_point(aes(fill = seeding.effectiveness.scale), 
                       shape = 21, color = "black", size = 1.5) +
            scale_fill_continuous_divergingx(palette = 'Tropic', mid = 0.5, n_interp = 11) +
            coord_flip() +
            theme_bw() +
            labs(x = "", y = expression(Songbird~differentials~log~frac(Vag, CS)), 
                 fill = "Seeding Efficacy", title = paste(bb, "Day", dd),
                 subtitle = "All genera")
        print(p)
    }
}

```

#### Genera with at least 1 ASV having more than 1 log difference
```{r}
for (bb in c("Feces", "Forearm", "Mouth")){
    for (dd in c(2, 30, 120, 180)){
        #dd=2
        dat <- songbird_wk2 %>% 
            filter(body_site==bb, days ==dd) %>%
            mutate(x = paste(p, c, o, f, g, sep = ";")) %>%
            group_by(x) %>%
            filter(any(centered.diff.CS>=1 | centered.diff.CS<=-1)) # filter dataset according to effect size
        dat_ft <- all_phylo$ASV[[paste0("Baby-", bb, "-", dd, ".0")]] %>% 
            transform_sample_counts(., function(x){x / sum(x)}) %>%
            otu_table() %>% as.matrix() %>% as.data.frame() %>%
            rownames_to_column(var = "ASV") %>%
            filter(ASV %in% dat$featureid) %>% 
            pivot_longer(-1, names_to = "sample_name", values_to = "rel_a") %>% 
            filter(rel_a>0) %>%
            merge(., dat %>% select(featureid, k:s, x), by.x = "ASV", by.y = 1)
        
        x.order = dat %>% group_by(x) %>% summarise(MM = median(centered.diff.CS)) %>% arrange(desc(MM))
        
        p <- dat %>% mutate(x = factor(x, levels = unique(x.order$x))) %>%
            ggplot(aes(x = x, y = -centered.diff.CS)) +
            annotate("rect", ymin = -Inf, ymax = 0, xmin = -Inf, xmax = Inf, fill = "#E41A1C", alpha = 0.1) +
            annotate("rect", ymin = 0, ymax = Inf, xmin = -Inf, xmax = Inf, fill = "#377EB8", alpha = 0.1) +
            geom_hline(yintercept = 0, color = "grey") +
            geom_point(aes(fill = seeding.effectiveness.scale), 
                       shape = 21, color = "black", size = 1.5) +
            scale_fill_continuous_divergingx(palette = 'Tropic', mid = 0.5, n_interp = 11) +
            coord_flip() +
            theme_bw() +
            labs(x = "", y = expression(Songbird~differentials~log~frac(Vag, CS)), 
                 fill = "Seeding Efficacy", title = paste(bb, "Day", dd),
                 subtitle = "Genus with at least 1 ASV had more than 1 log difference")
        print(p)
    }
}
```

####
```{r}
for (bb in c("Feces", "Forearm", "Mouth")){
    for (dd in c(2, 30, 120, 180)){
        #dd=2
        dat <- songbird_wk2 %>% 
            filter(body_site==bb, days ==dd) %>%
            mutate(x = paste(p, c, o, f, g, sep = ";"))
        
        %>%
            group_by(x) %>%
            filter(centered.diff.CS>=1 | centered.diff.CS<=-1)
        dat_ft <- all_phylo$ASV[[paste0("Baby-", bb, "-", dd, ".0")]] %>% 
            transform_sample_counts(., function(x){x / sum(x)}) %>%
            otu_table() %>% as.matrix() %>% as.data.frame() %>%
            rownames_to_column(var = "ASV") %>%
            filter(ASV %in% dat$featureid) %>% 
            pivot_longer(-1, names_to = "sample_name", values_to = "rel_a") %>% 
            filter(rel_a>0) %>%
            merge(., dat %>% select(featureid, k:s, x), by.x = "ASV", by.y = 1)
        
        p2 <- dat_ft %>% mutate(x = factor(x, levels = unique(x.order$x))) %>%
            ggplot(aes(x = x, y = rel_a)) +
            geom_boxplot(outlier.size = 1) +
            scale_y_continuous(breaks = c(1e-4, 1e-3, 1e-2, 1e-1, 1), labels =c("0.01%", "0.1%", "1%", "10%", "100%"), trans = "log10") +
            coord_flip() +
            theme_bw() +
            labs(x = "", y = "Relative Abundance in log scale", title = paste0("Day", dd))
        
        p3 = p + p2 + theme(axis.text.y = element_blank(), title = element_blank())
        print(p3)
        set_panel_size(g = patchworkGrob(p3), file = paste0(fig_path, "songbird_diff_", bb, "_g_day", dd, ".pdf"), width = unit(c(4, 3), "in"), height = unit(4*2.5*nrow(dat)/156, "in"), useDingbats = F )
    }
}


## filter by seeding effectiveness
for (dd in c(2, 30, 120, 180)){
    #dd=2
    dat <- songbird_wk2 %>% filter(body_site==bb, days ==dd) %>%
        mutate(x = paste(p, c, o, f, g, sep = ";")) %>%
        group_by(k, p, c, o, f, g) %>%
        filter(any(seeding.effectiveness.scale>=0.8))
    dat_ft <- all_phylo$ASV[[paste0("Baby-", bb, "-", dd, ".0")]] %>% 
        transform_sample_counts(., function(x){x / sum(x)}) %>%
        otu_table() %>% as.matrix() %>% as.data.frame() %>%
        rownames_to_column(var = "ASV") %>%
        filter(ASV %in% dat$featureid) %>% 
        pivot_longer(-1, names_to = "sample_name", values_to = "rel_a") %>% 
        filter(rel_a>0) %>%
        merge(., dat %>% select(featureid, k:s, x), by.x = "ASV", by.y = 1)
    
    x.order = dat %>% group_by(x, featureid) %>% summarise(MM = mean(Diff.CS)) %>% arrange(desc(MM))
    
    p <- dat %>% mutate(x = factor(x, levels = unique(x.order$x))) %>%
        ggplot(aes(x = x, y = -Diff.CS)) +
        annotate("rect", ymin = -Inf, ymax = 0, xmin = -Inf, xmax = Inf, fill = "#E41A1C", alpha = 0.1) +
        annotate("rect", ymin = 0, ymax = Inf, xmin = -Inf, xmax = Inf, fill = "#377EB8", alpha = 0.1) +
        geom_hline(yintercept = 0, color = "grey") +
        geom_point(aes(fill = seeding.effectiveness.scale), 
                   shape = 21, color = "black", size = 1.5) +
        scale_fill_distiller(palette = 'RdYlBu', direction = 1) +
        coord_flip() +
        theme_bw() +
        labs(x = "", y = expression(Songbird~differentials~log~frac(Vag, CS)), fill = "Seeding Efficacy", title = paste0("Day", dd))
    p2 <- dat_ft %>% mutate(x = factor(x, levels = unique(x.order$x))) %>%
        ggplot(aes(x = x, y = rel_a)) +
        geom_boxplot(outlier.size = 1) +
        scale_y_continuous(breaks = c(1e-4, 1e-3, 1e-2, 1e-1, 1), labels =c("0.01%", "0.1%", "1%", "10%", "100%"), trans = "log10") +
        coord_flip() +
        theme_bw() +
        labs(x = "", y = "Relative Abundance in log scale", title = paste0("Day", dd))
    
    p3 = p + p2 + theme(axis.text.y = element_blank(), title = element_blank())
    print(p3)
    set_panel_size(g = patchworkGrob(p3), file = paste0(fig_path, "songbird_diff_", bb, "_g_day", dd, "_v0.8.pdf"), width = unit(c(4, 3), "in"), height = unit(4*2.5*nrow(dat)/156, "in"), useDingbats = F )
}
```

### Plot against P.CS
```{r}

for (dd in c(2, 30, 120, 180)){
    #dd=2
    dat <- songbird_wk2 %>% filter(body_site==bb, days ==dd) %>%
        mutate(x = paste(p, c, o, f, g, sep = ";"))
    print(nrow(dat))
    next
    dat_ft <- all_phylo$ASV[[paste0("Baby-", bb, "-", dd, ".0")]] %>% 
        transform_sample_counts(., function(x){x / sum(x)}) %>%
        otu_table() %>% as.matrix() %>% as.data.frame() %>%
        rownames_to_column(var = "ASV") %>%
        filter(ASV %in% dat$featureid) %>% 
        pivot_longer(-1, names_to = "sample_name", values_to = "rel_a") %>% 
        filter(rel_a>0) %>%
        merge(., dat %>% select(featureid, k:s, x), by.x = "ASV", by.y = 1)
    
    x.order = dat %>% group_by(x, featureid) %>% summarise(MM = mean(P.CS)) %>% arrange(desc(MM))
    
    p <- dat %>% mutate(x = factor(x, levels = unique(x.order$x))) %>%
        ggplot(aes(x = x, y = P.CS)) +
        annotate("rect", ymin = 0.75, ymax = 1, xmin = -Inf, xmax = Inf, fill = "#E41A1C", alpha = 0.1) +
        annotate("rect", ymin = 0, ymax = 0.25, xmin = -Inf, xmax = Inf, fill = "#377EB8", alpha = 0.1) +
        geom_point(aes(fill = seeding.effectiveness.scale), 
                   shape = 21, color = "black", size = 1.5) +
        scale_fill_distiller(palette = 'RdYlBu', direction = 1) +
        scale_y_continuous(position = "right") +
        coord_flip() +
        theme_bw() +
        labs(x = "", y = "Relative probality in cesarean", fill = "Seeding Efficacy", title = paste0("Day", dd))
    p2 <- dat_ft %>% mutate(x = factor(x, levels = unique(x.order$x))) %>%
        ggplot(aes(x = x, y = rel_a)) +
        geom_boxplot(outlier.size = 1) +
        scale_y_continuous(breaks = c(1e-4, 1e-3, 1e-2, 1e-1, 1), labels =c("0.01%", "0.1%", "1%", "10%", "100%"), trans = "log10", position = "right") +
        coord_flip() +
        theme_bw() +
        labs(x = "", y = "Relative Abundance in log scale", title = paste0("Day", dd))
    
    p3 = p + p2 + theme(axis.text.y = element_blank(), title = element_blank())
    print(p3)
    set_panel_size(g = patchworkGrob(p3), file = paste0(fig_path, "songbird_diff_", bb, "_g_day", dd, "_v3.pdf"), width = unit(c(4, 3), "in"), height = unit(4*2.5*nrow(dat)/156, "in"), useDingbats = F )
}

```

```{r}
for (dd in c(2, 30, 120, 180)){
    #dd=2
    dat <- songbird_wk2 %>% filter(body_site==bb, days ==dd, abs(Diff.CS)>=0.7) %>%
        mutate(x = paste(p, c, o, f, g, sep = ";"))
    #print(nrow(dat))
    #next
    dat_ft <- all_phylo$ASV[[paste0("Baby-", bb, "-", dd, ".0")]] %>% 
        transform_sample_counts(., function(x){x / sum(x)}) %>%
        otu_table() %>% as.matrix() %>% as.data.frame() %>%
        rownames_to_column(var = "ASV") %>%
        filter(ASV %in% dat$featureid) %>% 
        pivot_longer(-1, names_to = "sample_name", values_to = "rel_a") %>% 
        filter(rel_a>0) %>%
        merge(., dat %>% select(featureid, k:s, x), by.x = "ASV", by.y = 1)
    
    x.order = dat %>% group_by(x, featureid) %>% summarise(MM = mean(P.CS)) %>% arrange(desc(MM))
    
    p <- dat %>% mutate(x = factor(x, levels = unique(x.order$x))) %>%
        ggplot(aes(x = x, y = P.CS)) +
        annotate("rect", ymin = 0.75, ymax = 1, xmin = -Inf, xmax = Inf, fill = "#E41A1C", alpha = 0.1) +
        annotate("rect", ymin = 0, ymax = 0.25, xmin = -Inf, xmax = Inf, fill = "#377EB8", alpha = 0.1) +
        geom_point(aes(fill = seeding.effectiveness.scale), 
                   shape = 21, color = "black", size = 1.5) +
        scale_fill_distiller(palette = 'RdYlBu', direction = 1) +
        scale_y_continuous(position = "right") +
        coord_flip() +
        theme_bw() +
        labs(x = "", y = "Relative probality in cesarean", fill = "Seeding Efficacy", title = paste0("Day", dd))
    p2 <- dat_ft %>% mutate(x = factor(x, levels = unique(x.order$x))) %>%
        ggplot(aes(x = x, y = rel_a)) +
        geom_boxplot(outlier.size = 1) +
        scale_y_continuous(breaks = c(1e-4, 1e-3, 1e-2, 1e-1, 1), labels =c("0.01%", "0.1%", "1%", "10%", "100%"), trans = "log10", position = "right") +
        coord_flip() +
        theme_bw() +
        labs(x = "", y = "Relative Abundance in log scale", title = paste0("Day", dd))
    
    p3 = p + p2 + theme(axis.text.y = element_blank(), title = element_blank())
    print(p3)
    set_panel_size(g = patchworkGrob(p3), file = paste0(fig_path, "songbird_diff_", bb, "_g_day", dd, "_v4.pdf"), width = unit(c(4, 3), "in"), height = unit(4*2.5*nrow(dat)/156, "in"), useDingbats = F )
}

```


## Summarizing ANCOM results
```{r}
dat_path = list.files(path = "../data/diff-analysis-new/ancom_all_results",
                     pattern = "*rds", full.names = T, include.dirs = F)

dat_nms <- (dat_path %>% str_split(., "/|\\.", simplify = T))[, 7]
dat_files <- lapply(dat_path, function(x){readRDS(x)})
names(dat_files) <- dat_nms

dat_flt <- lapply(dat_files, function(x){lapply(x, function(y){y$W.taxa %>% filter(detected_0.6==T)}) %>% 
        do.call("rbind", .) %>% 
        rownames_to_column(var = "body_site_days")}) %>% 
    do.call("rbind", .) %>%
    rownames_to_column(var = "level") %>%
    separate(level, into = c(NA, NA, "level", NA), sep = "_|\\.") %>%
    separate(body_site_days, into = c(NA, "body_sites", "days", NA, NA), sep = "-|\\.") %>%
    mutate(days = as.numeric(days))
```

```{r}
load("tmp_all_phylo.Rdata")
levels = dat_flt$level %>% unique
bodysites = dat_flt$body_sites %>% unique
timepoints = dat_flt$days %>% unique
for (ll in levels){
    for (bb in bodysites){
        for (tt in timepoints){
            dat = dat_flt %>% filter(level==ll, body_sites==bb, days==tt)
            dat_phylo = all_phylo[[ll]][[paste0("Baby-", bb, "-", tt, ".0")]] %>%
                prune_taxa(dat$Taxa_id, x = .) %>% 
                transform_sample_counts(., function(x){x / sum(x)})
            mf_phylo = sample_data(dat_phylo) %>% as.matrix() %>% as.data.frame() %>%
                rownames_to_column(var = "sample_name") %>%
                arrange(birth_mode_ms)
            plot_heatmap(dat_phylo, 
                         sample.label = "birth_mode_ms",
                         sample.order = mf_phylo$sample_name,
                         method = NULL, 
                         distance = NULL) %>% print()
        }
    }
}
```


