---
title: "Differential taxa analysis"
author: "Jincheng Wang"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, 
                      warning = FALSE, message = FALSE)
# Loading library here
library(conflicted)
library(tidyverse)
library(Ternary)
library(phyloseq)
library(colorspace)
library(patchwork)
library(ComplexHeatmap)
sessionInfo()
conflict_prefer("filter", "dplyr")

np = switch(Sys.info()[['sysname']], Windows = 1, Darwin = 4)


fig_path = "tmp_figs/"

col_birthmode = c("#377EB8", "#4DAF4A", "#E41A1C")
names(col_birthmode) = c("Vag", "CSseed", "CS")
```
```{r helpers}
set_panel_size <- function (p = last_plot(), g = ggplot2::ggplotGrob(p), file = NULL, margin = unit(1, "mm"), width = unit(4, "cm"), height = unit(4, "cm"), panel.size = T, msg = F, bitmap = "png", useDingbats = F, ...) {
    # This function is used to fine-tube the size of the panel
    #
    # Args:
    #   p: the ggplot object
    #   g: the ggplotGrob table for p, usually this parameter should not be changed
    #   file: file path
    #   margin: page margin, a unit object
    #   width: the exact unit object
    #   height: the exact unit object
    #   panel.size: whether the width and height is panel size or the overall graph
    #   msg: whether to print the grob table
    #   bitmap: whether to also export an exact version of bitmap: "png", "tiff", NULL
    #   ...: other ggsave parameters
    panels <- grep("panel", g$layout$name)
    panel_index_w <- unique(g$layout$l[panels])
    panel_index_h <- unique(g$layout$t[panels])
    nw <- length(panel_index_w)
    nh <- length(panel_index_h)
    if (panel.size){
        if (length(width)==1 & length(height)==1){
            g$widths[panel_index_w] <- rep(width, nw)
            g$heights[panel_index_h] <- rep(height, nh)
            if (!is.null(file)) {
                ggplot2::ggsave(file, g, width = grid::convertWidth(sum(g$widths) + 2 * margin, unitTo = "in", valueOnly = TRUE), height = grid::convertHeight(sum(g$heights) + 2 * margin, unitTo = "in", valueOnly = TRUE), useDingbats = useDingbats, ...)
                if (!is.null(bitmap)) {
                    ggplot2::ggsave(paste0(tools::file_path_sans_ext(file), ".", bitmap), g, width = grid::convertWidth(sum(g$widths) + 2 * margin, unitTo = "in", valueOnly = TRUE), height = grid::convertHeight(sum(g$heights) + 2 * margin, unitTo = "in", valueOnly = TRUE),  dpi = 600, ...)
                }
            }
        }
        else{
            g$widths[panel_index_w] <- width
            g$heights[panel_index_h] <- height
            if (!is.null(file)) {
                ggplot2::ggsave(file, g, width = grid::convertWidth(sum(g$widths) + 2 * margin, unitTo = "in", valueOnly = TRUE), height = grid::convertHeight(sum(g$heights) + 2 * margin, unitTo = "in", valueOnly = TRUE), useDingbats = useDingbats, ...)
                if (!is.null(bitmap)) {
                    ggplot2::ggsave(paste0(tools::file_path_sans_ext(file), ".", bitmap), g, width = grid::convertWidth(sum(g$widths) + 2 * margin, unitTo = "in", valueOnly = TRUE), height = grid::convertHeight(sum(g$heights) + 2 * margin, unitTo = "in", valueOnly = TRUE),  dpi = 600, ...)
                }
            }
        }
    }
    else{
        sum_panel_width = convertWidth(width - sum(g$widths[-panel_index_w]) - 2 * margin, unitTo = "in", valueOnly = TRUE)
        sum_panel_height = convertWidth(height - sum(g$heights[-panel_index_h]) - 2 * margin, unitTo = "in", valueOnly = TRUE)
        panel_width_r <- as.numeric(g$widths[panel_index_w])
        panel_height_r <- as.numeric(g$heights[panel_index_h])
        g$widths[panel_index_w] <- unit(panel_width_r/sum(panel_width_r)*sum_panel_width, units = "in")
        g$heights[panel_index_h] <- unit(panel_height_r/sum(panel_height_r)*sum_panel_height, units = "in")
        if (!is.null(file)) {
            ggplot2::ggsave(file, g, width = width, height = height, useDingbats = useDingbats, ...)
            if (!is.null(bitmap)) {
                ggplot2::ggsave(paste0(tools::file_path_sans_ext(file), ".", bitmap), g, width = grid::convertWidth(sum(g$widths) + 2 * margin, unitTo = "in", valueOnly = TRUE), height = grid::convertHeight(sum(g$heights) + 2 * margin, unitTo = "in", valueOnly = TRUE),  dpi = 600, ...)
            }
            print(g$widths[panel_index_w])
            print(g$heights[panel_index_h])
        }
    }
}

```

## Summarizing songbird resulst
### Examing songbird model fit
```{r}
dat_path = '../data/diff-analysis-new'
```
When performing songbird parameter summary, following parameters were tried:
```{r}
songbird_pp = read_csv("../data/diff-analysis-new/songbird-summary-output/TP-w-training-grid-search-parameters-set.csv") %>%
    mutate(across(everything(), ~trimws(.x))) %>%
    separate(body_site_days, into = c("body_site", "days"), sep = "-(?=\\d)") %>%
    mutate(days = as.numeric(days))
songbird_pp
```

```{r, eval=FALSE}
songbird_model_fits <- read.table(file = "../data/diff-analysis-new/songbird-summary-output/TP-w-training-grid-search-all-allowed-models4.tsv", header = T, sep = "\t")[, -1]

songbird_best_models <- songbird_model_fits %>% filter(best=="Yes") %>%  # select best model under different formula
    filter(grepl("country", formula)) # since all the formula with country as covariate performed better

songbird_best_models_print <- songbird_best_models %>% 
    mutate(model_CV = round(CV, 1),
           null_CV = round(baseline_CV, 1),
           q_squared = round(q_squared, 3)) %>%
    select(body_site, days, min_features:differential_prior,
           model_CV, null_CV, q_squared) %>%
    arrange(body_site, days) %>%
    full_join(., songbird_pp, by = c("body_site", "days")) %>% 
    write.table(file = "../results/Extended_Data_Table_Songbird_model_fit_statistics.tsv", sep = "\t", quote = F, row.names = F)
```
```{r}
songbird_rsl <- read.csv("../data/diff-analysis-new/songbird-summary-output/TP-w-training-best-model-processed3.tsv", sep = "\t", fill = F) %>% select(-1, -2, -starts_with("country")) %>% filter(grepl("country", model.para))

songbird_wk <- songbird_rsl %>% 
    select(body_site_days, featureid,
           X.T.Vag., X.T.CSseed.,
           starts_with("P."), Taxon, 
           starts_with("centered"),
           feature.frequency, seeding.effectiveness) %>%
    rename(P.VD = P.Vaginal., P.CSR = P.CS.seeded., P.CS = P.CS.,
           Diff.Vag = X.T.Vag., Diff.CSR = X.T.CSseed.) %>%
    separate(body_site_days, into = c(NA, "body_site", "days"), sep = "-") %>% 
    mutate(days = as.numeric(days)) %>%
    group_by(body_site, days) %>% 
    mutate(seeding.effectiveness.scale = pnorm(as.numeric(scale(seeding.effectiveness, center = mean(seeding.effectiveness), scale = T)))) %>%
    ungroup() %>%
    arrange(body_site, days, desc(seeding.effectiveness.scale)) %>%
    mutate(featureid = factor(featureid, levels = unique(featureid)), 
           Taxon = gsub(" ", "", Taxon),
           Taxon = gsub("__", "_", Taxon)) %>%
    separate(Taxon, into = c("k", "p", "c", "o", "f", "g", "s"), sep = ";",
             remove = F,
             fill = "right") %>%
    mutate(across(k:s, ~ifelse(is.na(.x), "-", .x)))

# check the distribution of seeding-effectiveness score
ggplot(songbird_wk, aes(x = seeding.effectiveness)) +
    geom_histogram(aes(color = as.factor(days), fill = as.factor(days)), alpha = 0.3, position = "identity") +
    facet_grid(body_site ~ .)

songbird_wk %>% group_by(body_site, days) %>% summarise(stats = Hmisc::smean.sd(seeding.effectiveness) %>% paste(collapse = "--"))


# songbird_wk_0.9 <- songbird_wk %>% 
#     filter(seeding.effectiveness.scale>=0.9, feature.frequency>=0.1) %>%
#     mutate(across(.cols = c(P.CS:P.VD, feature.frequency:seeding.effectiveness.scale), ~round(., 3)))
# songbird_wk_0.9 %>% pivot_wider(id_cols = c(body_site, days, Taxon, k:s), names_from = NULL, values_from = c(Diff.CS, Diff.CSR, seeding.effectiveness.scale, feature.frequency, P.VD, P.CSR, P.CS), names_repair = "minimal") %>% arrange(body_site, days, Taxon)
# songbird_wk_0.8 <- songbird_wk %>% 
#     filter(seeding.effectiveness.scale>=0.8, feature.frequency>=0.1) %>%
#     mutate(across(.cols = c(P.CS:P.VD, feature.frequency:seeding.effectiveness.scale), ~round(., 3)))
# 
# songbird_wk_0.8 %>% group_by(body_site, days) %>% summarize(N = n())
```
```{r}
phylo_trans = readRDS("phylo_transmission_analysis.Rdata")
mf_tmp <- sample_data(phylo_trans) %>% as.matrix() %>% as.data.frame() %>% rownames_to_column(var = "sample_name")
## Maternal ASV paranatal
mf_mm_day0 <- mf_tmp %>% filter((mom_baby=="Mom" & as.numeric(date_sampling_category_days_continuous)<=2)|body_site_corrected=="Gauze")
mf_mm_day0$body_site_corrected[mf_mm_day0$body_site_corrected=="Gauze"] = "Vagina"
mf_mm_day0$birth_mode_ms[mf_mm_day0$birth_mode_ms=="CSself"] = "CSseed"
mf_mm_day0_vagina <- mf_mm_day0 %>% filter(body_site_corrected=="Vagina") %>% split(., list(.$birth_mode_ms))
otu_mm_day0_vagina <- parallel::mclapply(mf_mm_day0_vagina, function(x){prune_samples(x$sample_name, phylo_trans) %>% 
        otu_table %>% as.matrix() %>% as.data.frame() %>%
        filter(rowSums(.>0)>0.1*ncol(.)) %>%
        row.names()}, mc.cores = np) %>%
    do.call("c", .) %>%
    unique() # only include otu existed in more than 10% of samples

songbird_wk2 <- songbird_wk %>%
    filter(feature.frequency>=0.1, p!="p_", c!="c_", o!="o_", f!="f_", p!="-", c!="-", o!="-", f!="-") %>%
    mutate(VaginaASV = featureid %in% otu_mm_day0_vagina)
load("diff_analysis_all_phylo.Rdata")
```
### Ternary plot
```{r}
plot_ternary = function(bb, dd, color_fun){
    TernaryPlot(point = "up",  alab = "P(Cesarean-seeded) <---", 
                blab = "P(Vaginal) --->", clab = "P(Cesarean) <---",
                lab.col = c( "#4DAF4A", "#377EB8", "#E41A1C"),
                lab.cex = 0.75,
                lab.offset = 0.15,
                
                grid.lines = 5,
                grid.minor.lines = 1,
                grid.col = c("#4DAF4A", "#377EB8", "#E41A1C"),
                grid.lty = "dotted",
                grid.lwd = 0.4,
                grid.minor.lty = "dotted",
                grid.minor.lwd = 0.2,
                grid.minor.col = c("#4DAF4A", "#377EB8", "#E41A1C"),
                
                padding = 0.12,
                
                main = paste0("Day ", dd),
                cex.main = 1,
                
                axis.col = "black",
                axis.labels=seq(0, 1, by = 0.2),
                axis.cex = 0.75,
                axis.lwd = 0.3,
                ticks.lwd = 0.3,
                
                clockwise = F)
    dat_ternary = songbird_wk %>% filter(body_site==bb, days==dd) %>% 
        select(P.CSR, P.VD, P.CS, seeding.effectiveness.scale)
    dat_ternary$col = color_fun(dat_ternary$seeding.effectiveness.scale)
    
    AddToTernary(points, dat_ternary[, 1:3], pch = 21, cex = 0.3, col = dat_ternary$col, bg = dat_ternary$col)
}


for (bb in c("Feces", "Forearm", "Mouth")){
    pdf(file = paste0(fig_path, "songbird_ternary_plot_", bb, ".pdf"), width = 6.6, height = 4.4, useDingbats = F, pointsize = 12)
    par(mfrow = c(1, 3), mar = rep(0.1, 4))
    for (dd in c(2, 30, 180)){
        color_fun = circlize::colorRamp2(seq(0, 1, 0.1), colors = sequential_hcl(11, palette = "Inferno"))
        plot_ternary(bb, dd, color_fun)
    }

    dev.off()
    #next
    # create the legend
    pdf(file = paste0(fig_path, "songbird_ternary_plot_", bb, "_legend.pdf"), width = 3, height = 1, pointsize = 8, useDingbats = F)
    par(mai = c(0.3, 0.1, 0.3, 0.1))
    image(x = seq(0,1,len=100), 
          y = 1,
          z = matrix(1:100,ncol=1),
          main = "Probability of coexistance in exposed babies",
          cex.main = 1, 
          col = color_fun(seq(0,1,len=100)),
          axes = FALSE, xlab = "", ylab = "")
    axis(1, at = seq(0.1, 0.9, 0.2), cex.axis = 1)
    dev.off()
    }
```

### Plots
```{r}
decontam = readRDS("decontam_result.Rds")
```
```{r, eval=FALSE}
target_taxa <- songbird_wk2 %>% 
    filter(body_site=="Feces", days==2, grepl("Streptococcus", Taxon)) %>%
    mutate(x = paste(p, c, o, f, g, sep = ";"))
ft_target <- all_phylo$ASV[[paste0("Baby-", bb, "-", dd, ".0")]] %>% 
    transform_sample_counts(., function(x){x / sum(x)}) %>%
    otu_table() %>% as.matrix() %>% as.data.frame() %>%
    rownames_to_column(var = "ASV") %>%
    filter(ASV %in% target_taxa$featureid) %>% 
    pivot_longer(-1, names_to = "sample_name", values_to = "rel_a") %>% 
    filter(rel_a>0) %>%
    merge(., target_taxa, by.x = "ASV", by.y = "featureid") %>%
    merge(., sample_data(all_phylo$ASV[[paste0("Baby-", bb, "-", dd, ".0")]]) %>% as.matrix %>% as.data.frame, by.x = "sample_name", by.y = 0)

ggplot(ft_target, aes(ASV, rel_a, color = birth_mode_ms)) +
    geom_boxplot() +
    stat_summary(geom = "point", fun = mean, position = position_dodge(width = 0.8)) +
    geom_text(aes(y = max(rel_a), label = Diff.CS)) +
    scale_x_discrete(breaks = ft_target$ASV, labels = ft_target$Taxon) +
    scale_y_continuous(trans = "log10") +
    coord_flip()
```
#### Top `pct` genus plots songbird differential
```{r}
pct = 0.2
for (bb in c("Feces", "Forearm", "Mouth")){
    p_list = list()
    max_n = 0
    for (dd in c(2, 30, 180)){
        #dd=2
        dat <- songbird_wk2 %>% filter(body_site==bb, days ==dd, !featureid %in% decontam$Row.names) %>% mutate(x = paste(p, c, o, f, g, sep = ";"))
        x.order = dat %>% group_by(x) %>% summarise(MM = median(centered.diff.CSseed)) %>% ungroup() %>% arrange(MM) 
        x.order2 = head(x.order, n = round(nrow(x.order)*pct)) %>%
            rbind(., tail(x.order, n = round(nrow(x.order)*pct)))
        dat <- dat %>% filter(x %in% x.order2$x) %>% mutate(x = factor(x, levels = unique(x.order2$x))) %>% arrange(x) 
        dat_sum <- dat %>% group_by(p, c, o, f, g, x) %>% summarise(med_seeding = median(seeding.effectiveness.scale), med_diff = median(centered.diff.CSseed), mean_seeding = round(mean(seeding.effectiveness.scale), 3), max_seeding = max(seeding.effectiveness.scale), VaginaASV = any(VaginaASV)) %>% mutate(g_label = ifelse(g %in% c("-", "g_"), f, gsub("g_", "", g)))
        
        p_list[[as.character(dd)]] = ggplot(dat_sum, aes(x = x, y = med_diff)) +
            coord_flip() +
            geom_bar(stat = "identity", aes(fill = max_seeding), color = "grey", size = 0.1) +
            geom_text(aes(y = ifelse(med_diff>0, -0.1, 0.1), label = g_label, hjust = ifelse(med_diff>0, 1, 0)), size = 6/.pt, show.legend = F) +
            scale_fill_continuous_sequential(palette = "Inferno", n_interp = 11, rev = F, begin = 0, end = 1, breaks = seq(0.1, 0.9, 0.2), limits = c(0, 1)) +
            theme_bw(base_size = 8) + theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), plot.margin = margin(0, 0, 0, 0), panel.grid.major.y = element_blank()) +
            labs(x = "", y = expression(Songbird~differentials~":"~log~"("~frac(Cesarean-seeded, Cesarean)~")"~ + K), fill = "Probability of coexistance in exposed babies", title = paste(bb, "Day", dd))
        max_n = max(nrow(dat_sum), max_n)
    }
    p = wrap_plots(p_list) + plot_layout(guides = "collect")
    p
    set_panel_size(g = patchworkGrob(p), file = paste0(fig_path, "songbird_diff_", bb, "_top", pct, "-g_CSref.pdf"), width = unit(2.2, "in"), height = unit(min(0.1*max_n, 4),"in"), useDingbats = F)
    
}
```
### Tables
```{r}
songbird_wk2 %>% mutate(x = paste(p, c, o, f, g, sep = ";")) %>%
    group_by(body_site, days) %>%
    slice_max(seeding.effectiveness.scale, n = 20) %>%
    arrange(body_site, days, Taxon, desc(seeding.effectiveness.scale)) %>%
    select(body_site, days, p:s, featureid, VaginaASV, seeding.effectiveness.scale, feature.frequency, P.VD, P.CSR, P.CS) %>%
    mutate(across(seeding.effectiveness.scale:P.CS, ~round(.x, 3)), across(p:s, ~gsub("^[[:lower:]]_", "", .x)), across(p:s, ~ifelse(.x %in% c("", "-"), "unknown", .x))) %>% 
    unite("Taxonomy", p:s, sep = ".") %>%
    write.table(file = "../data/diff-analysis-new/songbird-summary-output/songbird_top20_seedingeffectiveness_asv.tsv", sep = "\t", quote = F, row.names = F)

songbird_wk2 %>% mutate(x = paste(p, c, o, f, g, sep = ";")) %>%
    group_by(body_site, days) %>%
    slice_max(seeding.effectiveness.scale, prop = 0.2) %>%
    arrange(body_site, days, Taxon, desc(seeding.effectiveness.scale)) %>%
    select(body_site, days, p:s, featureid, VaginaASV, seeding.effectiveness.scale, feature.frequency, P.VD, P.CSR, P.CS) %>%
    mutate(across(seeding.effectiveness.scale:P.CS, ~round(.x, 3)), across(p:s, ~gsub("^[[:lower:]]_", "", .x)), across(p:s, ~ifelse(.x %in% c("", "-"), "unknown", .x))) %>% 
    unite("Taxonomy", p:s, sep = ".") %>%
    write.table(file = "../data/diff-analysis-new/songbird-summary-output/songbird_top0.2_seedingeffectiveness_asv.tsv", sep = "\t", quote = F, row.names = F)

songbird_wk2 %>% mutate(x = paste(p, c, o, f, g, sep = ";")) %>%
    group_by(body_site, days) %>%
    filter(seeding.effectiveness.scale>=0.8) %>%
    arrange(body_site, days, Taxon, desc(seeding.effectiveness.scale)) %>%
    select(body_site, days, p:s, featureid, VaginaASV, seeding.effectiveness.scale, feature.frequency, P.VD, P.CSR, P.CS) %>%
    mutate(across(seeding.effectiveness.scale:P.CS, ~round(.x, 3)), across(p:s, ~gsub("^[[:lower:]]_", "", .x)), across(p:s, ~ifelse(.x %in% c("", "-"), "unknown", .x))) %>% 
    unite("Taxonomy", p:s, sep = ".") %>%
    write.table(file = "../data/diff-analysis-new/songbird-summary-output/songbird_seedingeffectiveness0.8_asv.tsv", sep = "\t", quote = F, row.names = F)

songbird_wk2 %>% mutate(x = paste(p, c, o, f, g, sep = ";")) %>%
    group_by(body_site, days) %>%
    filter(seeding.effectiveness.scale>=0.8) %>%
    arrange(body_site, days, Taxon, desc(seeding.effectiveness.scale)) %>%
    select(body_site, days, p:s, VaginaASV, seeding.effectiveness.scale, feature.frequency, P.VD, P.CSR, P.CS) %>%
    mutate(across(seeding.effectiveness.scale:P.CS, ~round(.x, 3)), across(p:s, ~gsub("^[[:lower:]]_", "", .x)), across(p:s, ~ifelse(.x %in% c("", "-"), "unknown", .x))) %>% 
    unite("Taxonomy", p:s, sep = ".") %>%
    group_by(body_site, days, VaginaASV) %>% summarise(N = n()) %>% mutate(Pct = N/sum(N)) %>% filter(VaginaASV)

songbird_wk2 %>% mutate(x = paste(p, c, o, f, g, sep = ";")) %>%
    split(., f = list(.$body_site, .$days)) %>%
    lapply(., function(x){rbind(slice_max(x, centered.diff.CSseed, prop = 0.2), slice_min(x, centered.diff.CSseed, prop = 0.2))}) %>%
    data.table::rbindlist(.) %>%
    arrange(body_site, days, Taxon, desc(centered.diff.CSseed)) %>%
    select(body_site, days, p:s, featureid, VaginaASV, centered.diff.CSseed, seeding.effectiveness.scale, feature.frequency, P.VD, P.CSR, P.CS) %>%
    mutate(across(seeding.effectiveness.scale:P.CS, ~round(.x, 3)), across(p:s, ~gsub("^[[:lower:]]_", "", .x)), across(p:s, ~ifelse(.x %in% c("", "-"), "unknown", .x))) %>% 
    unite("Taxonomy", p:s, sep = ".") %>%
    write.table(file = "../data/diff-analysis-new/songbird-summary-output/songbird_topbottom0.2_differential_asv.tsv", sep = "\t", quote = F, row.names = F)
```
## Summarizing ANCOM results
```{r}
dat_path = list.files(path = "../data/diff-analysis-new/ancom_all_results/ancom_w_country",  pattern = "*rds", full.names = T, include.dirs = F)

dat_nms <- (dat_path %>% str_split(., "/|\\.", simplify = T))[, 8]
dat_files <- lapply(dat_path, function(x){readRDS(x)})
names(dat_files) <- dat_nms

dat_flt <- lapply(dat_files, function(x){lapply(x, function(y){y$W.taxa %>% filter(detected_0.6==T)}) %>%
        do.call("rbind", .) %>%
        rownames_to_column(var = "body_site_days")}) %>%
    do.call("rbind", .) %>%
    rownames_to_column(var = "level") %>%
    separate(level, into = c(NA, NA, "level", NA), sep = "_|\\.") %>%
    separate(body_site_days, into = c(NA, "body_sites", "days", NA, NA), sep = "-|\\.") %>%
    mutate(days = as.numeric(days))
dat_flt$Taxa_id[dat_flt$level!="ASV"] = NA

write.table(dat_flt, file = "../data/diff-analysis-new/ancom_all_results/ancom_w_country_all_rsl.txt", sep = "\t", quote = F, row.names = F)
```

```{r}
dat_flt %>% filter(level=="Genus") %>% arrange(body_sites, days) %>% View

```

## Summarizing pairwise ANCOM results
```{r}
dat_path = list.files(path = "../data/diff-analysis-new/ancom_all_results/ancom_w_country_pairwise/",  pattern = "*rds", full.names = T, include.dirs = F)
dat_nms <- ((dat_path %>% str_split(., "/|\\.", simplify = T))[, 9] %>% str_split(., "_", simplify = T))[, 4]

dat_files <- lapply(dat_path, function(x){readRDS(x)})
names(dat_files) <- dat_nms

summarize_ancom_output <- function(ancom_out, main_var){
    ancom_out = ancom_out
    ancom_out_tst = ancom_out$W.taxa %>% as.data.frame()
    ancom_out_mf = ancom_out$mf %>% select(Sample.ID, all_of(main_var))
    ancom_out_ft = ancom_out$ft %>% merge(., ancom_out_mf, by = 1) %>% select(Sample.ID, all_of(main_var), all_of(ancom_out_tst$otu.names)) %>% pivot_longer(-c(1, 2), names_to = "otu.names", values_to = "count") %>% group_by(across(main_var), Sample.ID) %>% mutate(rel_a = count/sum(count)) %>% ungroup()
    ancom_out_feature_means <- ancom_out_ft %>% 
        group_by(otu.names, across(main_var)) %>%
        summarise(mean_rel_a = mean(rel_a), med_rel_a = median(rel_a)) %>% 
        ungroup() %>% 
        pivot_wider(id_cols = otu.names, 
                    names_from = main_var, 
                    values_from = c(mean_rel_a, med_rel_a),
                    names_sep = ".")
    ancom_out_f = merge(ancom_out_tst, ancom_out_feature_means, by = "otu.names")
    return(ancom_out_f)
}

dat_sum = list()
for (i in seq_along(dat_files)){
    nm = names(dat_files)[i]
    dat_sum_ = list()
    for (j in seq_along(dat_files[[i]])){
        grp = names(dat_files[[i]])[j]
        dat_sum_[[grp]] = lapply(dat_files[[i]][[j]], function(x){summarize_ancom_output(x, "birth_mode_ms")}) %>% data.table::rbindlist(., idcol = "Comp", fill = T)
    }
    dat_sum[[nm]] = data.table::rbindlist(dat_sum_, idcol = "body_site_days", use.names = T)
}

dat_sum_asv_flt = dat_sum$ASV %>% filter(detected_0.6) %>% separate(body_site_days, into = c(NA, "Sampling Site", "Days"), sep = "-") %>% mutate(Flag_mean = case_when(Comp=="CS-Vag" ~ mean_rel_a.CS>mean_rel_a.Vag, Comp=="CS-CSseed" ~ mean_rel_a.CS>mean_rel_a.CSseed, Comp=="CSseed-Vag" ~ mean_rel_a.CSseed>mean_rel_a.Vag), Flag_med = case_when(Comp=="CS-Vag" ~ med_rel_a.CS>med_rel_a.Vag, Comp=="CS-CSseed" ~ med_rel_a.CS>med_rel_a.CSseed, Comp=="CSseed-Vag" ~ med_rel_a.CSseed>med_rel_a.Vag), Comp = factor(Comp, levels = c("CS-Vag", "CSseed-Vag", "CS-CSseed")), Days = as.numeric(Days)) %>% ungroup() %>% mutate(across(Domain:Species, ~gsub("^[[:lower:]]_", "", .x)), across(Domain:Species, ~ifelse(.x %in% c("", "-"), "unknown", .x))) %>% arrange(`Sampling Site`, Days, Comp, Phylum, Class, Order, Family, Genus, Species)

dat_sum_flt = lapply(dat_sum, function(x){ x %>% filter(detected_0.6) %>% separate(body_site_days, into = c(NA, "Sampling Site", "Days"), sep = "-") %>% mutate(Flag_mean = case_when(Comp=="CS-Vag" ~ mean_rel_a.CS>mean_rel_a.Vag, Comp=="CS-CSseed" ~ mean_rel_a.CS>mean_rel_a.CSseed, Comp=="CSseed-Vag" ~ mean_rel_a.CSseed>mean_rel_a.Vag), Flag_med = case_when(Comp=="CS-Vag" ~ med_rel_a.CS>med_rel_a.Vag, Comp=="CS-CSseed" ~ med_rel_a.CS>med_rel_a.CSseed, Comp=="CSseed-Vag" ~ med_rel_a.CSseed>med_rel_a.Vag), Comp = factor(Comp, levels = c("CS-Vag", "CSseed-Vag", "CS-CSseed")), Days = as.numeric(Days)) %>% ungroup()}) %>%
    data.table::rbindlist(., use.names = T, idcol = "levels") %>%
    mutate(across(Domain:Species, ~gsub("^[[:lower:]]_", "", .x)), across(Domain:Species, ~ifelse(.x %in% c("", "-"), "unknown", .x))) %>% 
    arrange(levels, `Sampling Site`, Days, Comp, Phylum, Class, Order, Family, Genus, Species)


write.table(dat_sum_asv_flt, file = "../data/diff-analysis-new/ancom_all_results/ancom_w_country_pairwise_ASV_rsl.txt", sep = "\t", quote = F, row.names = F)

write.table(dat_sum_flt, file = "../data/diff-analysis-new/ancom_all_results/ancom_w_country_pairwise_all_rsl.txt", sep = "\t", quote = F, row.names = F)
```

## Check the genus level call by Maaslin2, ANCOM, and LefSe
```{r}
genus_diff_comp <- readxl::read_excel("~/Projects/seeding-study/data/diff-analysis-new/Genus_CSvVag_ANCOMLefSeMaaslin2.xlsx")

genus_diff_comp_ <- genus_diff_comp %>% mutate(Dummy = 1) %>%pivot_wider(id_cols = c(Body_site:enrich_group), names_from = methods, values_from = Dummy)
write.table(genus_diff_comp_, file = "../results/diff_comp_3methods.txt", sep = "\t", quote = F, row.names = F)
```

