---
title: "Traditional Beta"
author: "Jincheng Wang"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, warning = FALSE, message = FALSE)
# Loading library here
library(tidyverse)
library(ggbeeswarm)

sessionInfo()
np = switch(Sys.info()[['sysname']], Windows = 1, Darwin = 4)
fig_path = "tmp_figs/"
```

```{r}
theme_Pub <- function(base_size=10) {
    require(grid)
    require(ggthemes)
    (theme_foundation(base_size=base_size)
        + theme(plot.title = element_text(face = "bold",
                                          size = rel(1.2), hjust = 0.5),
                text = element_text(),
                panel.background = element_rect(colour = NA),
                plot.background = element_rect(colour = NA),
                panel.border = element_rect(colour = NA),
                axis.title = element_text(face = "bold", size = rel(1), color = "black"),
                axis.title.y = element_text(angle=90, vjust =2),
                axis.title.x = element_text(vjust = -0.2),
                axis.text = element_text(size = rel(1), color = "black"),
                axis.line = element_line(color = "black", size = 1/.pt),
                axis.ticks = element_line(color = "black", size = 1/.pt),
                panel.grid.major = element_line(color = "grey", size = 0.1),
                panel.grid.minor = element_line(color = "grey", size = 0.1),
                legend.key = element_rect(colour = NA),
                legend.position = "right",
                legend.direction = "vertical",
                legend.key.size= unit(0.4, "cm"),
                legend.title = element_text(face="italic"),
                legend.text=element_text(size = rel(0.8)),
                plot.margin=unit(c(1,0.5,0.5,0.5),"lines"),
                strip.background=element_rect(colour="black",fill="black"),
                strip.text = element_text(face="bold", color = "white", size = rel(1))
        ))
}


set_panel_size <- function (p = last_plot(), g = ggplot2::ggplotGrob(p), file = NULL, margin = unit(1, "mm"), width = unit(4, "cm"), height = unit(4, "cm"), panel.size = T, msg = F, bitmap = "png", useDingbats = F, ...) {
    # This function is used to fine-tube the size of the panel
    #
    # Args:
    #   p: the ggplot object
    #   g: the ggplotGrob table for p, usually this parameter should not be changed
    #   file: file path
    #   margin: page margin, a unit object
    #   width: the exact unit object
    #   height: the exact unit object
    #   panel.size: whether the width and height is panel size or the overall graph
    #   msg: whether to print the grob table
    #   bitmap: whether to also export an exact version of bitmap: "png", "tiff", NULL
    #   ...: other ggsave parameters
    panels <- grep("panel", g$layout$name)
    panel_index_w <- unique(g$layout$l[panels])
    panel_index_h <- unique(g$layout$t[panels])
    nw <- length(panel_index_w)
    nh <- length(panel_index_h)
    if (panel.size){
        if (length(width)==1 & length(height)==1){
            g$widths[panel_index_w] <- rep(width, nw)
            g$heights[panel_index_h] <- rep(height, nh)
            if (!is.null(file)) {
                ggplot2::ggsave(file, g, width = grid::convertWidth(sum(g$widths) + 2 * margin, unitTo = "in", valueOnly = TRUE), height = grid::convertHeight(sum(g$heights) + 2 * margin, unitTo = "in", valueOnly = TRUE), useDingbats = useDingbats, ...)
                if (!is.null(bitmap)) {
                    ggplot2::ggsave(paste0(tools::file_path_sans_ext(file), ".", bitmap), g, width = grid::convertWidth(sum(g$widths) + 2 * margin, unitTo = "in", valueOnly = TRUE), height = grid::convertHeight(sum(g$heights) + 2 * margin, unitTo = "in", valueOnly = TRUE),  dpi = 600, ...)
                }
            }
        }
        else{
            g$widths[panel_index_w] <- width
            g$heights[panel_index_h] <- height
            if (!is.null(file)) {
                ggplot2::ggsave(file, g, width = grid::convertWidth(sum(g$widths) + 2 * margin, unitTo = "in", valueOnly = TRUE), height = grid::convertHeight(sum(g$heights) + 2 * margin, unitTo = "in", valueOnly = TRUE), useDingbats = useDingbats, ...)
                if (!is.null(bitmap)) {
                    ggplot2::ggsave(paste0(tools::file_path_sans_ext(file), ".", bitmap), g, width = grid::convertWidth(sum(g$widths) + 2 * margin, unitTo = "in", valueOnly = TRUE), height = grid::convertHeight(sum(g$heights) + 2 * margin, unitTo = "in", valueOnly = TRUE),  dpi = 600, ...)
                }
            }
        }
    }
    else{
        sum_panel_width = convertWidth(width - sum(g$widths[-panel_index_w]) - 2 * margin, unitTo = "in", valueOnly = TRUE)
        sum_panel_height = convertWidth(height - sum(g$heights[-panel_index_h]) - 2 * margin, unitTo = "in", valueOnly = TRUE)
        panel_width_r <- as.numeric(g$widths[panel_index_w])
        panel_height_r <- as.numeric(g$heights[panel_index_h])
        g$widths[panel_index_w] <- unit(panel_width_r/sum(panel_width_r)*sum_panel_width, units = "in")
        g$heights[panel_index_h] <- unit(panel_height_r/sum(panel_height_r)*sum_panel_height, units = "in")
        if (!is.null(file)) {
            ggplot2::ggsave(file, g, width = width, height = height, useDingbats = useDingbats, ...)
            if (!is.null(bitmap)) {
                ggplot2::ggsave(paste0(tools::file_path_sans_ext(file), ".", bitmap), g, width = grid::convertWidth(sum(g$widths) + 2 * margin, unitTo = "in", valueOnly = TRUE), height = grid::convertHeight(sum(g$heights) + 2 * margin, unitTo = "in", valueOnly = TRUE),  dpi = 600, ...)
            }
            print(g$widths[panel_index_w])
            print(g$heights[panel_index_h])
        }
    }
}


```

## Import files
### baby and maternal samples
```{r}
# import metadata
Convex_all <- read.delim("../results/ConvexHullOutput.csv", header = T, sep = ",", na.strings = c("", "NA"), stringsAsFactors = F) %>% select(-X) %>% mutate(birth_mode = factor(birth_mode, levels = c("Mom", "Vag", "CSseed", "CS")), body_site2 = ifelse(body_site=="Forearm", "Skin", body_site))

Convex_6mon <- read.delim("../results/ConvexHullOutput_6mon.csv", header = T, sep = ",", na.strings = c("", "NA"), stringsAsFactors = F) %>% select(-X) %>% mutate(birth_mode = factor(birth_mode, levels = c("Mom", "Vag", "CSseed", "CS")), body_site2 = ifelse(body_site=="Forearm", "Skin", body_site))


clr_bm = c("#e41a1c", "#4daf4a", "#377eb8", "#6a3d9a")
names(clr_bm) = c("CS", "CSseed", "Vag", "Mom")
```

## Plots
```{r}

ggplot(Convex_all, aes(x = birth_mode, y = convexhull_volume)) +
    geom_boxplot(aes(fill = birth_mode), alpha = 0.5, outlier.shape = NA, lwd = 0.2) +
    geom_quasirandom(size = 1, width = 0.2, alpha = 0.5, aes(color = birth_mode), show.legend = F) +
    facet_wrap(.~body_site2, scales = "free_y") +
    scale_x_discrete(labels = c("Mom", "Vaginal", "Cesarean\n-seeded", "Cesarean")) +
    scale_color_manual(values = clr_bm) +
    scale_fill_manual(values = clr_bm) +
    theme_Pub(base_size = 8) + theme(aspect.ratio = 0.6, panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
    labs(x = "", y = "Convex Hull (Volume)", title = "All")
set_panel_size(file = "../results/Figure-ConvexHull-R.pdf", width = unit(2, "in"), height = unit(1.2, "in"))

ggplot(Convex_6mon, aes(x = birth_mode, y = convexhull_volume)) +
    geom_boxplot(aes(fill = birth_mode), alpha = 0.5, outlier.shape = NA, lwd = 0.2) +
    geom_quasirandom(size = 1, width = 0.2, alpha = 0.5, aes(color = birth_mode), show.legend = F) +
    facet_wrap(.~body_site2, scales = "free_y") +
    scale_x_discrete(labels = c("Mom", "Vaginal", "Cesarean\n-seeded", "Cesarean")) +
    scale_color_manual(values = clr_bm) +
    scale_fill_manual(values = clr_bm) +
    theme_Pub(base_size = 8) + theme(aspect.ratio = 0.6, panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
    labs(x = "", y = "Convex Hull (Volume)", title = "First 6 months")
set_panel_size(file = "../results/Figure-ConvexHull-6mon-R.pdf", width = unit(2, "in"), height = unit(1.2, "in"))
```

```{r}
# By countries

Convex_6mon_2 <- Convex_6mon %>% mutate(country = substr(subjectid_unique, 1, 2), country = case_when(country =="BL" ~ "Bolivia", country %in% c("Ch", "CH") ~ "Chile", country  =="ES" ~ "Spain", T ~ "USA") %>% factor(levels = c("USA", "Chile", "Spain", "Bolivia")))
for (bb in c("Feces", "Mouth", "Skin")){
    p = ggplot(Convex_6mon_2 %>% filter(country!="Bolivia", body_site2==bb), aes(x = birth_mode, y = convexhull_volume)) +
        geom_boxplot(aes(fill = birth_mode), alpha = 0.5, outlier.shape = NA, lwd = 0.2, show.legend = F) +
        geom_quasirandom(size = 1, width = 0.2, alpha = 0.5, aes(color = birth_mode), show.legend = F) +
        facet_grid(.~country) +
        scale_x_discrete(labels = c("Mom" = "Mom", "Vag" = "Vaginal", "CSseed" = "Cesarean\n-seeded", "CS" = "Cesarean"), drop = F) +
        scale_y_continuous(n.breaks = 4) +
        scale_color_manual(values = clr_bm) +
        scale_fill_manual(values = clr_bm) +
        theme_Pub(base_size = 8) + theme(aspect.ratio = 0.6, plot.title = element_text(hjust = 0), plot.title.position = "plot", panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
        labs(x = "", y = "Convex Hull (Volume)", title = paste0(bb, "- First 6 months"))
    print(p)
    set_panel_size(file = paste0( "../results/Figure-ConvexHull-6mon-R-", bb, ".pdf"), width = unit(2.2, "in"), height = unit(1.2, "in"))
}

Convex_all_2 <- Convex_all %>% mutate(country = substr(subjectid_unique, 1, 2), country = case_when(country =="BL" ~ "Bolivia", country %in% c("Ch", "CH") ~ "Chile", country  =="ES" ~ "Spain", T ~ "USA"))

ggplot(Convex_6mon_2 %>% filter(country!="Bolivia"), aes(x = birth_mode, y = convexhull_volume)) +
        geom_boxplot(aes(fill = birth_mode), alpha = 0.5, outlier.shape = NA, lwd = 0.2) +
        geom_quasirandom(size = 1, width = 0.2, alpha = 0.5, aes(color = birth_mode), show.legend = F) +
        facet_wrap(.~body_site2+country, scales = "free_y", ncol = 3) +
        scale_x_discrete(labels = c("Mom" = "Mom", "Vag" = "Vaginal", "CSseed" = "Cesarean\n-seeded", "CS" = "Cesarean"), drop = F) +
        scale_y_continuous(n.breaks = 4) +
        scale_color_manual(values = clr_bm) +
        scale_fill_manual(values = clr_bm) +
        theme_Pub(base_size = 8) + theme(aspect.ratio = 0.6, plot.title = element_text(hjust = 0), plot.title.position = "plot", panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
        labs(x = "", y = "Convex Hull (Volume)", title = paste0(cc, "- First 6 months"))
```


