---
title: "Source Tracking Analysis"
author: "Jincheng Wang"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r setup, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, warning = FALSE, message = FALSE)
# Loading library here
library(tidyverse)
library(extrafont)
# library(biomformat)
# library(ape)
# library(qiime2R)
library(phyloseq)
library(ComplexHeatmap)
library(igraph)
sessionInfo()

np = switch(Sys.info()[['sysname']], Windows = 1, Darwin = 4)
```


## Pre-processing (no need to rerun)
### baby and maternal samples (rarefied tables)
```{r, eval=FALSE}
# all body sites to use for now
ss <- c("Feces", "Mouth", "Forearm", "Vagina", "Right_Areola", "Nose")

# baby qza address
bb_qza_dirs <- paste0("../data/split-data/Baby-", ss[1:3])
# mom qza address
mm_qza_dirs <- paste0("../data/split-data/Mom-", ss)

# import qza tables
bb_qza <- parallel::mclapply(bb_qza_dirs, FUN = function(x){read_qza(paste0(x, "/rarefy-table.qza"))}, mc.cores = np)
names(bb_qza) <- paste0("Baby-", ss[1:3])
#lapply(bb_qza, function(x){x$data %>% dim})

mm_qza <- parallel::mclapply(mm_qza_dirs, FUN = function(x){read_qza(paste0(x, "/rarefy-table.qza"))}, mc.cores = np )
names(mm_qza) <- paste0("Mom-", ss)

#lapply(mm_qza, function(x){x$data %>% dim})


# import metadata
mf <- read.delim("../data/processed-data/Metadata_Baby_Seeding_all_samples_final.txt", header = T, sep = "\t", na.strings = c("", "NA"), stringsAsFactors = F)
## extract metadata for
mf_ss <- mf %>% filter(sample_name %in% (sapply(c(bb_qza, mm_qza), FUN = function(x)colnames(x$data)) %>% unlist()))
mf_ss$body_site_corrected[mf_ss$body_site_corrected=="Right_Forearm"] = "Forearm"
```

### Gauze samples (this needs to be udpated once uploading gauze sequences into qiita)
```{r, eval=FALSE}
ft_qza_all <- read_qza("~/Dropbox/41-JCHWANG-NYU/Projects/05-BabyProject2017RobKnight/GauzeSeq/3-deblur/SA-P1-P3_deblur_no-mitochondria-no-chloroplast_table.qza")
mf_gauze <- read.table("~/Dropbox/41-JCHWANG-NYU/Projects/05-BabyProject2017RobKnight/GauzeSeq/0-Doc/Mapping_baby_seeding_gauze.txt", header = T, sep = "\t")
ft_tbl_gauze <- ft_qza_all$data[, mf_gauze$sample_name] %>% as.data.frame %>% filter(rowSums(.)>0)
```

### Create phyloseq object
```{r, eval=FALSE}
otu_ss <- parallel::mclapply(c(bb_qza, mm_qza), function(x){otu_table(x$data %>% as.data.frame %>% select(any_of(mf_ss$sample_name)) %>% filter(rowSums(.)>0), taxa_are_rows = T)}, mc.cores = np)

## import the otu table into phyloseq
otu_ss_phylo <- do.call("merge_phyloseq", otu_ss)

taxa_qza <- read_qza("../data/processed-data/taxonomy.qza")
taxa_tbl <- taxa_qza$data %>% mutate(Taxon = gsub(pattern = "__", replacement = "_", Taxon)) %>% separate(Taxon, into = c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species"), sep = "; ", remove = T)
taxa_tbl$Domain[is.na(taxa_tbl$Domain)] <- "k_"
taxa_tbl$Phylum[is.na(taxa_tbl$Phylum)] <- "p_"
taxa_tbl$Class[is.na(taxa_tbl$Class)] <- "c_"
taxa_tbl$Order[is.na(taxa_tbl$Order)] <- "o_"
taxa_tbl$Family[is.na(taxa_tbl$Family)] <- "f_"
taxa_tbl$Genus[is.na(taxa_tbl$Genus)] <- "g_"
taxa_tbl$Species[is.na(taxa_tbl$Species)] <- "s_"

taxa_all <- taxa_tbl %>% filter(Feature.ID %in% rownames(otu_table(otu_ss_phylo))) %>% select(Feature.ID, Domain:Species) %>% column_to_rownames(var = "Feature.ID") %>% as.matrix() %>% tax_table()

ss_phylo <- merge_phyloseq(otu_ss_phylo, taxa_all, sample_data(mf_ss %>% column_to_rownames(var = "sample_name")))


taxa_qza_gauze <- read_qza("~/Dropbox/41-JCHWANG-NYU/Projects/05-BabyProject2017RobKnight/GauzeSeq/3-deblur/taxonomy_gg13_8.qza")
taxa_gauze_tbl <- taxa_qza_gauze$data %>% filter(Feature.ID %in% rownames(ft_tbl_gauze)) %>% mutate(Taxon = gsub(pattern = "__", replacement = "_", Taxon)) %>% separate(Taxon, into = c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species"), sep = "; ", remove = T)
taxa_gauze_tbl$Domain[is.na(taxa_gauze_tbl$Domain)] <- "k_"
taxa_gauze_tbl$Phylum[is.na(taxa_gauze_tbl$Phylum)] <- "p_"
taxa_gauze_tbl$Class[is.na(taxa_gauze_tbl$Class)] <- "c_"
taxa_gauze_tbl$Order[is.na(taxa_gauze_tbl$Order)] <- "o_"
taxa_gauze_tbl$Family[is.na(taxa_gauze_tbl$Family)] <- "f_"
taxa_gauze_tbl$Genus[is.na(taxa_gauze_tbl$Genus)] <- "g_"
taxa_gauze_tbl$Species[is.na(taxa_gauze_tbl$Species)] <- "s_"
taxa_gauze_tbl <- taxa_gauze_tbl %>% select(Feature.ID, Domain:Species) %>% column_to_rownames(var = "Feature.ID") %>% as.matrix() %>% tax_table()

phylo_gauze <- merge_phyloseq(otu_table(ft_tbl_gauze, taxa_are_rows = T), taxa_gauze_tbl, sample_data(mf_gauze %>% column_to_rownames(var = "sample_name")))
phylo_gauze_5k <- rarefy_even_depth(phylo_gauze, sample.size = 5000, rngseed = 20, replace = F, trimOTUs = T)

phylo_wk <- merge_phyloseq(ss_phylo, phylo_gauze_5k) %>% prune_taxa(taxa_sums(.)>0, .)
saveRDS(phylo_wk, file = "tmp_phylo_wk_transmission.Rdata")
```
## Analysis
```{r}
ss <- c("Feces", "Mouth", "Forearm", "Vagina", "Right_Areola", "Nose")

phylo_wk = readRDS("tmp_phylo_wk_transmission.Rdata")
mf_wk <- sample_data(phylo_wk) %>% as.matrix() %>% as.data.frame() %>% rownames_to_column(var = "sample_name")


## Maternal ASV paranatal
mf_mm_day0 <- mf_wk %>% filter((mom_baby=="Mom" & as.numeric(date_sampling_category_days_continuous)==0)|body_site_corrected=="Gauze")
mf_mm_day0_lst <- mf_mm_day0 %>% split(., list(.$body_site_corrected))
mf_mm_day0_lst$Vagina <- rbind(mf_mm_day0_lst$Vagina, mf_mm_day0_lst$Gauze)
mf_mm_day0_lst$Gauze <- NULL
otu_mm_day0_lst <- parallel::mclapply(mf_mm_day0_lst, function(x){prune_samples(x$sample_name, phylo_wk) %>% otu_table %>% as.matrix() %>% as.data.frame %>% filter(rowSums(.>0)>0.1*ncol(.))}, mc.cores = np) # only include otu existed in more than 10% of samples

## Baby ASVs
mf_bb_lst <- mf_wk %>% filter(mom_baby=="Baby") %>% split(., list(.$body_site_corrected, .$birth_mode_ms))
otu_baby_lst <- parallel::mclapply(mf_bb_lst, function(x){prune_samples(x$sample_name, phylo_wk) %>% otu_table %>% as.matrix() %>% as.data.frame %>% filter(rowSums(.>0)>0.1*ncol(.))}, mc.cores = np)
```

### Plot individual samples and ASVs on heatmap
```{r}
get_heatmap <- function(birthmode, row_cluster=NULL){
    bm = birthmode # the string of birth mode, ["CS", "Vag", "CSseed"]
    mf_bb_tmp1 <- mf_bb_tmp %>% filter(sample_name %in% colnames(otu_bb_tmp[[paste(ss_b, bm, sep = ".")]])) %>% arrange(as.numeric(date_sampling_category_days_continuous))
    
    ## create the matrix for heatmap
    otu_mat1 <- otu_mm_tmp[otu_cc, ] %>% merge(., otu_bb_tmp[[paste(ss_b, bm, sep = ".")]][, mf_bb_tmp1$sample_name], by = 0, all.x = T) %>% column_to_rownames(var = "Row.names")
    ### convert to log scale
    otu_mat1 = log10(otu_mat1/5000)
    ### convert na or Inf to be -5, a value that is beyond the actual data range
    otu_mat1[otu_mat1==-Inf] = -5
    otu_mat1[is.na(otu_mat1)] = -5
    
    ## create the cluster for dendrogram of ASV based on baby samples only if it is Vag
    if (bm=="Vag"){
        row_cluster <- hclust(dist(otu_mat1[,  mf_bb_tmp1$sample_name]))
        row_cluster_flag = T
    } else {
        if (is.null(row_cluster)){stop("please provide row dendrogram or cluster")}
        row_cluster_flag = F
    }
    
    ## metadata for the heatmap
    meta_mat1 <- rbind(mf_mm_tmp, mf_bb_tmp1)
    ## data table for column annotation
    df_col <- meta_mat1 %>% ungroup %>% select(mom_baby, date_sampling_category_days_continuous) %>% 
        mutate(mom_baby = factor(mom_baby, levels = c("Mom", "Baby")),
               date_sampling_category_days_continuous = as.numeric(date_sampling_category_days_continuous),
               Days = case_when(date_sampling_category_days_continuous<=7 ~ "0-7",
                                date_sampling_category_days_continuous<=30 ~ "14-30",
                                date_sampling_category_days_continuous>=240 ~ ">=240",
                                T ~ as.character(date_sampling_category_days_continuous)),
               Days =  factor(Days, levels = c("0-7","14-30","60","90","120","150","180","210",">=240")),
               date_sampling_category_days_continuous = NULL)
    
    ## color scheme for the heatmap cells
    mat_col_fun = circlize::colorRamp2(c(-5, -4, -3.3, -2.6, -1.9, -1.2, -0.5), c("grey60","#253494", "#2c7fb8", "#41b6c4", "#7fcdbb", "#c7e9b4", "#ffffcc"))
    
    Days_col = c('#fff7f3','#fde0dd','#fcc5c0','#fa9fb5','#f768a1','#dd3497','#ae017e','#7a0177','#49006a')
    names(Days_col) <- df_col$Days %>% unique
    
    col_ha1 = columnAnnotation(mom_baby = df_col$mom_baby, col = list(mom_baby=c("Mom" = '#fdcdac', "Baby" = '#b3e2cd')), show_annotation_name = F,
                               Days = anno_block(gp = gpar(fill = Days_col), labels = names(Days_col), labels_gp = gpar(col = "black", fontsize = 6)),
                               annotation_name_gp = gpar(fontsize = 7), 
                               annotation_legend_param = list(mom_baby = list(labels_gp = gpar(fontsize = 7), title_gp = gpar(fontsize = 7, fontface = "bold"))))
    p1 <- Heatmap(otu_mat1, 
                  
                  name = "Relative abundance",
                  heatmap_legend_param = list(at = c(-4, -3.3, -2.6, -1.9, -1.2, -0.5), labels = c("0.01%", "0.05%", "0.25%", "1.25%", "6.25%", "31.25%"),
                                              labels_gp = gpar(fontsize = 6), title_gp = gpar(fontsize = 7, fontface = "bold")),
                  
                  column_title = bm,
                  
                  cluster_rows = row_cluster,
                  cluster_columns = F,
                  show_column_names = F,
                  show_row_names = F,
                  row_dend_reorder = row_cluster_flag,
                  
                  col = mat_col_fun,
                  
                  top_annotation = col_ha1,
                  
                  row_dend_width = unit(15, "mm"),
                  
                  column_split = df_col$Days,
                  column_gap = unit(rep(0, 8), "mm"),
                  cluster_column_slices = F,
                  
                  height = unit(7/.pt, "mm")*dim(otu_mat1)[1],
                  width = unit(0.7/.pt, "mm")*dim(otu_mat1)[2])
    return(p1)
}
for (ss_m in ss){
    #ss_m = ss[1]
    for (ss_b in ss[1:3]){
        #ss_b = ss[1]
        # select mother samples
        mf_mm_tmp <- mf_mm_day0 %>% filter(body_site_corrected==ss_m)
        otu_mm_tmp <- otu_mm_day0_lst[[ss_m]] 
        
        # select baby samples
        mf_bb_tmp <- mf_wk %>% filter(mom_baby=="Baby", body_site_corrected==ss_b)
        otu_bb_tmp <- otu_baby_lst[grepl(ss_b, names(otu_baby_lst))]
        
        otu_bb_all <- lapply(otu_bb_tmp, rownames) %>% do.call("c", .) %>% unique # all otu from babies, regardless birth mode
        
        otu_cc <- intersect(rownames(otu_mm_tmp), otu_bb_all) # common otu between maternal and baby samples
        
        p_vag <- get_heatmap("Vag")
        p_csr <- get_heatmap("CSseed", row_cluster = row_dend(p_vag))
        p_cs <- get_heatmap("CS", row_cluster = row_dend(p_vag))
        
        pdf(paste0("tmp_figs/compare_asv_individual_m-", ss_m, "_b-", ss_b, ".pdf"), width = ((nrow(mf_bb_tmp)+3*nrow(mf_mm_tmp))*0.7/.pt+60)/25.4, height = length(otu_cc)*7/.pt*1.2/25.4, useDingbats = F)
        draw(p_vag + p_csr + p_cs, column_title = paste0("Mom.", ss_m, " vs Baby.", ss_b))
        dev.off()
        
    }
}

```

### Plot average of baby samples by birth mode and timepoitn and ASVs on heatmap
```{r}
mm_day0_asv_all <- lapply(otu_mm_day0_lst, rownames) %>% do.call("c", .) %>% unique
df_row0 <- data.frame(ASV = mm_day0_asv_all)
for (ss_m in ss){
    df_row0[[ss_m]] = df_row0$ASV %in% rownames(otu_mm_day0_lst[[ss_m]])
}
df_row0 <- merge(df_row0, tax_table(phylo_wk), by.x = "ASV", by.y = 0, all.x = T) %>% mutate(across(Domain:Species, ~gsub(pattern = "^[[:lower:]]_(.+)", replacement = "\\1", .x)), Index = paste0("ASV", seq(n()))) %>% unite("Taxa", Domain:Index, sep = ";")


get_heatmap2 <- function(birthmode, row_cluster=NULL){
    bm = birthmode # the string of birth mode, ["CS", "Vag", "CSseed"]
    
    ## create the matrix for heatmap
    otu_mat_bb_tmp <- otu_bb_tmp_avg[[paste(ss_b, bm, sep = ".")]] %>% mutate(date_sampling_category_days_continuous = as.numeric(date_sampling_category_days_continuous)) %>% pivot_wider(id_cols = ASV, names_from = date_sampling_category_days_continuous, values_from = Count) %>% column_to_rownames(var = "ASV")
    otu_mat1 <- otu_mm_tmp_avg[otu_cc, ,drop = F] %>% merge(., otu_mat_bb_tmp, by = 0, all.x = T) %>% column_to_rownames(var = "Row.names")
    ### convert to log scale
    otu_mat1 = log10(otu_mat1/5000)
    ### convert na or Inf to be -5, a value that is beyond the actual data range
    otu_mat1[otu_mat1==-Inf] = -5
    otu_mat1[is.na(otu_mat1)] = -5
    
    ## create the cluster for dendrogram of ASV based on baby samples only if it is Vag
    if (bm=="Vag"){
        row_cluster <- hclust(dist(otu_mat1[, -1]))
        row_cluster_flag = T
    } else {
        if (is.null(row_cluster)){stop("please provide row dendrogram or cluster")}
        row_cluster_flag = F
    }
    
    ## metadata for the heatmap
    
    ## data table for column annotation
    df_col <- data.frame(Col.lab = colnames(otu_mat1)) %>%
        mutate(mom_baby = factor(c("Mom", rep("Baby", ncol(otu_mat1)-1)), levels = c("Mom", "Baby")),
               Days = as.numeric(c(0, colnames(otu_mat1)[-1])),
               Days = case_when(Days<=7 ~ "0-7",
                                Days<=30 ~ "14-30",
                                Days>=240 ~ ">=240",
                                T ~ as.character(Days)),
               Days =  factor(Days, levels = c("0-7","14-30","60","90","120","150","180","210",">=240")))
    
    ## color scheme for the heatmap cells
    mat_col_fun = circlize::colorRamp2(c(-5, -4, -3.3, -2.6, -1.9, -1.2, -0.5), c("grey60","#253494", "#2c7fb8", "#41b6c4", "#7fcdbb", "#c7e9b4", "#ffffcc"))
    
    Days_col = c('#fff7f3','#fde0dd','#fcc5c0','#fa9fb5','#f768a1','#dd3497','#ae017e','#7a0177','#49006a')
    names(Days_col) <- df_col$Days %>% unique
    
    col_ha1 = columnAnnotation(mom_baby = df_col$mom_baby, col = list(mom_baby=c("Mom" = '#fdcdac', "Baby" = '#b3e2cd')), show_annotation_name = F,
                               Days = anno_block(gp = gpar(fill = Days_col), labels = names(Days_col), labels_gp = gpar(col = "black", fontsize = 6)),
                               annotation_name_gp = gpar(fontsize = 7), 
                               annotation_legend_param = list(mom_baby = list(labels_gp = gpar(fontsize = 7), title_gp = gpar(fontsize = 7, fontface = "bold"))))
    
    df_row <- df_row0 %>% filter(ASV %in% otu_cc) %>% select(-all_of(ss_m)) %>% mutate(across(-c(ASV, Taxa), ~ifelse(.x, "Y", "N")))
    df_row2 = df_row %>% select(-c(ASV, Taxa))
    df_row2_col = lapply(colnames(df_row2), function(x){c("Y" = "blue", "N" = "white")}) 
    names(df_row2_col) = colnames(df_row2)
    row_ha1 = rowAnnotation(df = df_row2, col = df_row2_col, gp = gpar(col = "black"), show_legend = F, 
                            annotation_name_side = "top", annotation_name_gp = gpar(fontsize = 7))
    
    p1 <- Heatmap(otu_mat1,
                  name = "Relative Abundance",
                  heatmap_legend_param = list(at = c(-4, -3.3, -2.6, -1.9, -1.2, -0.5), labels = c("0.01%", "0.05%", "0.25%", "1.25%", "6.25%", "31.25%"),
                                              labels_gp = gpar(fontsize = 6), title_gp = gpar(fontsize = 7, fontface = "bold")),
                  
                  column_title = bm,
                  
                  cluster_rows = row_cluster,
                  cluster_columns = F,
                  show_column_names = F,
                  row_dend_reorder = row_cluster_flag,
                  
                  col = mat_col_fun,
                  rect_gp = gpar(col = "grey", lwd = 0.5),
                  
                  top_annotation = col_ha1,
                  left_annotation = if(bm=="Vag"){row_ha1}else{NULL},
                  
                  row_names_gp = gpar(fontsize = 7), 
                  row_labels = df_row$Taxa,
                  row_names_side = "right",
                  
                  row_dend_width = unit(15, "mm"),
                  
                  column_split = df_col$Days,
                  column_gap = unit(rep(0, 8), "mm"),
                  cluster_column_slices = F,
                  
                  
                  
                  height = unit(7/.pt, "mm")*dim(otu_mat1)[1],
                  width = unit(10/.pt, "mm")*dim(otu_mat1)[2])
    
    return(p1)
}
for (ss_m in ss){
    #ss_m = ss[1]
    for (ss_b in ss[1:3]){
        #ss_b = ss[1]
        # select mother samples
        otu_mm_tmp <- otu_mm_day0_lst[[ss_m]] 
        otu_mm_tmp_avg <- rowMeans(otu_mm_tmp) %>% data.frame(MomD0 = .)

        # select baby samples
        mf_bb_tmp <- mf_wk %>% filter(mom_baby=="Baby", body_site_corrected==ss_b)
        otu_bb_tmp <- otu_baby_lst[grepl(ss_b, names(otu_baby_lst))]
        otu_bb_tmp_avg <- parallel::mclapply(otu_bb_tmp, function(x){x %>% rownames_to_column(var = "ASV") %>% pivot_longer(names_to = "sample_name", values_to = "Count", -1) %>% merge(., mf_bb_tmp, by = "sample_name", all.x = T) %>% group_by(ASV, birth_mode_ms, date_sampling_category_days_continuous) %>% summarise(Count = mean(Count)) %>% ungroup()}, mc.cores = np)
        
        otu_bb_all <- lapply(otu_bb_tmp, rownames) %>% do.call("c", .) %>% unique # all otu from babies, regardless birth mode
        otu_cc <- intersect(rownames(otu_mm_tmp_avg), otu_bb_all) # common otu between maternal and baby samples
        
        p_vag <- get_heatmap2("Vag")
        p_csr <- get_heatmap2("CSseed", row_cluster = row_dend(p_vag))
        p_cs <- get_heatmap2("CS", row_cluster = row_dend(p_vag))
        
        
        pdf(paste0("tmp_figs/compare_asv_avg_m-", ss_m, "_b-", ss_b, ".pdf"), width = (57*10/.pt)*2.5/25.4, height = length(otu_cc)*7/.pt*1.4/25.4, useDingbats = F)
        draw(p_vag + p_csr + p_cs, column_title = paste0("Mom.", ss_m, " vs Baby.", ss_b), merge_legend = TRUE, heatmap_legend_side = "bottom", 
    annotation_legend_side = "bottom")
        dev.off()
        
    }
}
```

<!-- ### Plot average of baby samples by birth mode and timepoint and species on heatmap -->

<!-- ```{r} -->
<!-- phylo_wk = readRDS("tmp_phylo_wk_transmission.Rdata") -->

<!-- ## Maternal ASV paranatal -->
<!-- mf_mm_day0 <- mf_wk %>% filter(mom_baby=="Mom", as.numeric(date_sampling_category_days_continuous)==0) -->
<!-- mf_mm_day0_lst <- mf_mm_day0 %>% split(., list(.$body_site_corrected)) -->

<!-- otu_mm_day0_lst <- parallel::mclapply(mf_mm_day0_lst, function(x){prune_samples(x$sample_name, phylo_wk) %>% otu_table %>% as.matrix() %>% as.data.frame %>% filter(rowSums(.>0)>0.1*ncol(.))}, mc.cores = np) # only include otu existed in more than 10% of samples -->

<!-- ## Baby ASVs -->
<!-- mf_bb_lst <- mf_wk %>% filter(mom_baby=="Baby") %>% split(., list(.$body_site_corrected, .$birth_mode_ms)) -->
<!-- otu_baby_lst <- parallel::mclapply(mf_bb_lst, function(x){prune_samples(x$sample_name, phylo_wk) %>% otu_table %>% as.matrix() %>% as.data.frame %>% filter(rowSums(.>0)>0.1*ncol(.))}, mc.cores = np) -->
<!-- ``` -->


### Network
#### Maternal vagina
```{r}
ss <- c("Vagina", "Feces", "Mouth", "Forearm", "Right_Areola", "Nose")

fun1 <- function(x, y){
    return(c(paste0(x, "-", y), x))
}
tt <- ""
for (ss_m in ss[-6]){
    tt <- fun1(tt, ss_m)
}
tt <- sub("^-", "", tt)
tt <- tt[!tt==""]

asv_mm_day0_all <- lapply(seq_along(otu_mm_day0_lst), function(x){data.frame(ASV = rownames(otu_mm_day0_lst[[x]]), Bodysite = names(otu_mm_day0_lst)[[x]])}) %>% do.call("rbind",.)

asv_mm_day0_filt <- asv_mm_day0_all %>% mutate(Bodysite = factor(Bodysite, levels = ss)) %>% arrange(Bodysite, ASV) %>% group_by(ASV) %>%
    summarise(Grp = paste(Bodysite, collapse = "."), N_site = n())
```

```{r}
asv_mm_day0_filt_v <- asv_mm_day0_filt %>% filter(grepl("Vagina", Grp)) %>% 
    mutate(Grp2 = case_when(Grp=="Vagina" ~ "Vagina.Only",
                            N_site <=2 ~ Grp,
                            grepl("Vagina.Feces.", Grp) ~ "Vagina.Feces.Others",
                            grepl("Vagina.Forearm.", Grp) ~ "Vagina.Forearm.Others",
                            T ~ "Vagina.Others")) %>%
    mutate(Grp2 = factor(Grp2, levels = c("Vagina.Only", "Vagina.Feces", "Vagina.Feces.Others", "Vagina.Forearm", "Vagina.Forearm.Others", "Vagina.Others"))) %>%
    ungroup %>% arrange(Grp2, ASV)
nrow(asv_mm_day0_filt_v)
asv_mm_day0_filt_v$Grp2 %>% table(useNA = "ifany")


mf_bb_wk <- mf_wk %>% filter(mom_baby=="Baby", date_sampling_category_days %in% c("Day_30", "Day_90", "Day_240"))
asv_bb_tmp <- list()
for (dd in c("Day_30", "Day_90", "Day_240")){
    mf_tmp_lst <- mf_bb_wk %>% filter(date_sampling_category_days==dd) %>% split(., list(.$body_site_corrected, .$birth_mode_ms))
    asv_bb_tmp[[dd]] <- lapply(names(mf_tmp_lst), function(x){otu_baby_lst[[x]][, mf_tmp_lst[[x]]$sample_name] %>% filter(rowSums(.)>0) %>% rownames_to_column(var = "ASV") %>% select(ASV) %>% mutate(sample = paste(x, dd, sep = '.'))}) %>% do.call("rbind", .)
        
}
asv_bb_tmp <- do.call("rbind", asv_bb_tmp)

n_max <- asv_bb_tmp %>% separate(sample, into = paste0("V", seq(3)), sep = "\\.") %>% group_by(V2, V3) %>% summarise(N=n()) %>% pull(N) %>% max(c(., nrow(asv_mm_day0_filt_v)))
p_list <- list()
for (bm in c("Vag", "CSseed", "CS")){
    #break
    tmp_tb1 <- asv_bb_tmp %>% filter(grepl(paste0("\\<", bm, "\\>"), sample)) %>% merge(., asv_mm_day0_filt_v, by = "ASV", all.x = T) %>% mutate(date = str_extract(sample, "Day_\\d+"), bodysite = str_split(sample, pattern = "\\.", simplify = T)[, 1]) %>% arrange(date, bodysite, Grp2, ASV)

    tmp_tb1$xx[tmp_tb1$date=="Day_30"] <- 0
    tmp_tb1$yy[tmp_tb1$date=="Day_30"] <- seq(sum(tmp_tb1$date=="Day_30")) + (n_max - sum(tmp_tb1$date=="Day_30"))/2
    
    tmp_tb1$xx[tmp_tb1$date=="Day_90"] <- seq(sum(tmp_tb1$date=="Day_90")) + (n_max-sum(tmp_tb1$date=="Day_90"))/2
    tmp_tb1$yy[tmp_tb1$date=="Day_90"] <- n_max*1.2
    
    tmp_tb1$xx[tmp_tb1$date=="Day_240"] <- n_max*1.2
    tmp_tb1$yy[tmp_tb1$date=="Day_240"] <- seq(sum(tmp_tb1$date=="Day_240")) + (n_max - sum(tmp_tb1$date=="Day_240"))/2
    
    tmp_tb1_sum <- tmp_tb1 %>% group_by(date, bodysite, Grp2) %>% summarise(N = n()) %>% mutate(Pct = round(N/sum(N), 3), date = factor(date, levels = c("Day_30", "Day_90", "Day_240")))  %>% filter(!is.na(Grp2))
    
    bb_text <- tmp_tb1 %>% group_by(date, bodysite) %>% summarise(N = n(), xx = range(xx) %>% mean, yy = range(yy) %>% mean)
    
    tmp_tb2 <- asv_mm_day0_filt_v %>% mutate(xx = seq(n()) + (n_max-n())/2, yy = -5)
    tmp_tb2$Grp2 %>% table
    mm_text <- tmp_tb2 %>% group_by(Grp2) %>% summarise(N = n(), xx = range(xx) %>% mean, yy = -5) %>% mutate(Pct = round(N/sum(N)*100,1), Label = paste0(N, "(", Pct, "%)"))
    
    tmp_tb3 <- merge(tmp_tb1, tmp_tb2, by = c("ASV", "Grp2"), suffixes = c(".bb", ".mm"))
    
    bb_col <- c("#F8766D","#00BA38","#619CFF")
    names(bb_col) <- c("Feces", "Forearm", "Mouth")
    
    mm_col <- c('purple','black','#F8766D', 'orange', '#00BA38', 'grey')
    names(mm_col) <- c("Vagina.Only", "Vagina.Feces", "Vagina.Feces.Others", "Vagina.Forearm", "Vagina.Forearm.Others", "Vagina.Others")
    p_list[[bm]] <- ggplot(data = tmp_tb1, aes(x = xx, y = yy)) +
        geom_segment(data = tmp_tb3, aes(x = xx.mm, xend = xx.bb, y = yy.mm, yend = yy.bb, color = Grp2), size = 0.3) +
        geom_point(aes(fill = bodysite), colour = "transparent", shape = 22, size = 3) +
        geom_point(data = tmp_tb2, aes(x = xx, y = yy, color = Grp2), shape = 15, size = 3) +
        geom_label(data = bb_text, aes(label = N), size = 7/.pt) +
        geom_label_repel(data = mm_text, aes(label = Label), size = 7/.pt, ) +
        scale_fill_manual(values = bb_col) +
        scale_color_manual(values= mm_col) +
        theme_bw(base_size = 15) + theme(aspect.ratio = 1, panel.grid = element_blank(), axis.line = element_blank(), axis.text = element_blank(), axis.ticks = element_blank()) +
        labs(x = "", y = "", fill = "Baby Body Site", color = "", title = bm)
        
    print(p_list[[bm]])
    
    # ggplot(tmp_tb1_sum, aes(date, Pct, color = Grp2)) +
    #     geom_line(aes(group = Grp2)) +
    #     facet_grid(.~bodysite)
}

wrap_plots(p_list) + plot_layout(guides = "collect") & theme(legend.position = "bottom", legend.box = "vertical")
ggsave("tmp_figs/asv_shared_mm_vagina.pdf", width = 21, useDingbats = F)
```


#### Maternal feces
```{r}
asv_mm_day0_filt_v <- asv_mm_day0_filt %>% filter(grepl("Feces", Grp)) %>% 
    mutate(Grp2 = case_when(Grp=="Feces" ~ "Feces.Only",
                            Grp=="Feces.Right_Areola" ~ "Feces.Others",
                            N_site <=2 ~ Grp,
                            grepl("Vagina.Feces.", Grp) ~ "Vagina.Feces.Others",
                            grepl("Feces.Forearm.", Grp) ~ "Feces.Forearm.Others",
                            T ~ "Feces.Others")) %>% 
    mutate(Grp2 = factor(Grp2, levels = c("Feces.Only", "Vagina.Feces", "Vagina.Feces.Others", "Feces.Forearm", "Feces.Forearm.Others", "Feces.Mouth", "Feces.Others"))) %>%
    ungroup %>% arrange(Grp2, ASV)
nrow(asv_mm_day0_filt_v)
asv_mm_day0_filt_v$Grp2 %>% table(useNA = "ifany")


mf_bb_wk <- mf_wk %>% filter(mom_baby=="Baby", date_sampling_category_days %in% c("Day_30", "Day_90", "Day_240"))

asv_bb_tmp <- list()
for (dd in c("Day_30", "Day_90", "Day_240")){
    mf_tmp_lst <- mf_bb_wk %>% filter(date_sampling_category_days==dd) %>% split(., list(.$body_site_corrected, .$birth_mode_ms))
    asv_bb_tmp[[dd]] <- lapply(names(mf_tmp_lst), function(x){otu_baby_lst[[x]][, mf_tmp_lst[[x]]$sample_name] %>% filter(rowSums(.)>0) %>% rownames_to_column(var = "ASV") %>% select(ASV) %>% mutate(sample = paste(x, dd, sep = '.'))}) %>% do.call("rbind", .)
        
}
asv_bb_tmp <- do.call("rbind", asv_bb_tmp)

n_max <- asv_bb_tmp %>% separate(sample, into = paste0("V", seq(3)), sep = "\\.") %>% group_by(V2, V3) %>% summarise(N=n()) %>% pull(N) %>% max(c(., nrow(asv_mm_day0_filt_v)))
p_list <- list()
for (bm in c("Vag", "CSseed", "CS")){
    #break
    tmp_tb1 <- asv_bb_tmp %>% filter(grepl(paste0("\\<", bm, "\\>"), sample)) %>% merge(., asv_mm_day0_filt_v, by = "ASV", all.x = T) %>% mutate(date = str_extract(sample, "Day_\\d+"), bodysite = str_split(sample, pattern = "\\.", simplify = T)[, 1]) %>% arrange(date, bodysite, Grp2, ASV)

    tmp_tb1$xx[tmp_tb1$date=="Day_30"] <- 0
    tmp_tb1$yy[tmp_tb1$date=="Day_30"] <- seq(sum(tmp_tb1$date=="Day_30")) + (n_max - sum(tmp_tb1$date=="Day_30"))/2
    
    tmp_tb1$xx[tmp_tb1$date=="Day_90"] <- seq(sum(tmp_tb1$date=="Day_90")) + (n_max-sum(tmp_tb1$date=="Day_90"))/2
    tmp_tb1$yy[tmp_tb1$date=="Day_90"] <- n_max*1.2
    
    tmp_tb1$xx[tmp_tb1$date=="Day_240"] <- n_max*1.2
    tmp_tb1$yy[tmp_tb1$date=="Day_240"] <- seq(sum(tmp_tb1$date=="Day_240")) + (n_max - sum(tmp_tb1$date=="Day_240"))/2
    
    tmp_tb1_sum <- tmp_tb1 %>% group_by(date, bodysite, Grp2) %>% summarise(N = n()) %>% mutate(Pct = round(N/sum(N), 3), date = factor(date, levels = c("Day_30", "Day_90", "Day_240")))  %>% filter(!is.na(Grp2))
    
    bb_text <- tmp_tb1 %>% group_by(date, bodysite) %>% summarise(N = n(), xx = range(xx) %>% mean, yy = range(yy) %>% mean)
    
    tmp_tb2 <- asv_mm_day0_filt_v %>% mutate(xx = seq(n()) + (n_max-n())/2, yy = -5)
    tmp_tb2$Grp2 %>% table
    mm_text <- tmp_tb2 %>% group_by(Grp2) %>% summarise(N = n(), xx = range(xx) %>% mean, yy = -5) %>% mutate(Pct = round(N/sum(N)*100,1), Label = paste0(N, "(", Pct, "%)"))
    
    tmp_tb3 <- merge(tmp_tb1, tmp_tb2, by = c("ASV", "Grp2"), suffixes = c(".bb", ".mm"))
    
    bb_col <- c("#F8766D","#00BA38","#619CFF")
    names(bb_col) <- c("Feces", "Forearm", "Mouth")
    
    mm_col <- c('#F8766D', 'black', 'purple', 'orange', '#00BA38', "#619CFF", 'grey')
    names(mm_col) <- c("Feces.Only", "Vagina.Feces", "Vagina.Feces.Others", "Feces.Forearm", "Feces.Forearm.Others", "Feces.Mouth", "Feces.Others")
    p_list[[bm]] <- ggplot(data = tmp_tb1, aes(x = xx, y = yy)) +
        geom_segment(data = tmp_tb3, aes(x = xx.mm, xend = xx.bb, y = yy.mm, yend = yy.bb, color = Grp2), size = 0.3) +
        geom_point(aes(fill = bodysite), colour = "transparent", shape = 22, size = 3) +
        geom_point(data = tmp_tb2, aes(x = xx, y = yy, color = Grp2), shape = 15, size = 3) +
        geom_label(data = bb_text, aes(label = N), size = 7/.pt) +
        geom_label_repel(data = mm_text, aes(label = Label), size = 7/.pt, ) +
        scale_fill_manual(values = bb_col) +
        scale_color_manual(values= mm_col) +
        theme_bw(base_size = 15) + theme(aspect.ratio = 1, panel.grid = element_blank(), axis.line = element_blank(), axis.text = element_blank(), axis.ticks = element_blank()) +
        labs(x = "", y = "", fill = "Baby Body Site", color = "", title = bm)
        
    print(p_list[[bm]])
    
    # ggplot(tmp_tb1_sum, aes(date, Pct, color = Grp2)) +
    #     geom_line(aes(group = Grp2)) +
    #     facet_grid(.~bodysite)
}

wrap_plots(p_list) + plot_layout(guides = "collect") & theme(legend.position = "bottom", legend.box = "vertical")
ggsave("tmp_figs/asv_shared_mm_feces.pdf", width = 21, useDingbats = F)
```